### ISSUE TITLE
使用定位模块后无法在地图中进行定位

### ISSUE THREAD

**Issue by ganwei4353** [VirgilClyne/iRingo#106]
導入定位模塊和香港地圖模塊，打開iPhone地圖后，左下角還是顯示“高德地圖”，右下角就好像登入了我的gmail賬號。但是實際導航，輸入地點后，老是轉圈不能使用。將這兩個模塊關閉后，使用地圖就能正常導航，還需要修復一下，謝謝！

**Comment by WordlessEcho** [comment]
长时间未有回复，关闭issue
Close due to no response.
