### ISSUE TITLE
适配APIv3（iOS 16、iPadOS 16和macOS Ventura）上的天气

### ISSUE THREAD

**Issue by eli9966** [VirgilClyne/iRingo#107]
ios16 天气接口更新为v3，原模块无法直接套用

**Comment by eli9966** [comment]
部分报错信息
![image](https://user-images.githubusercontent.com/94114651/172364353-d933e652-0c86-474a-af44-2e9a5b5ec0ff.png)

**Comment by WordlessEcho** [comment]
模块本身在重构而且又遇上这次iOS大更新，所以还要很长时间才能好

**Comment by young61308** [comment]
> ios16 天气接口更新为v3，原模块无法直接套用

我也是遇到这个问题，ios16下这个模块失效了，作者辛苦了

**Comment by WordlessEcho** [comment]
各位好，beta版的模块已经适配了最新的天气，并趋于稳定
[Loon](https://github.com/VirgilClyne/iRingo/blob/beta/plugin/Weather.beta.plugin?raw=true), [Quantumult X](https://github.com/VirgilClyne/iRingo/blob/beta/qxrewrite/Weather.beta.qxrewrite?raw=true), [Surge (Shadowrocket)](https://github.com/VirgilClyne/iRingo/blob/beta/sgmodule/Weather.beta.sgmodule?raw=true), [Stash](https://github.com/VirgilClyne/iRingo/blob/beta/stoverride/Weather.beta.stoverride?raw=true)
如果您需要调整设置，请配合beta版的BoxJS使用： https://raw.githubusercontent.com/VirgilClyne/iRingo/beta/box/iRingo.beta.boxjs.json
或是使用如下argument：
```
Switch=true&NextHour.Switch=true&NextHour.Source=www.weatherol.cn&AQI.Switch=true&AQI.Targets=HJ6332012&AQI.Local.Switch=true&AQI.Local.Standard=WAQI_InstantCast&AQI.Source=www.weatherol.cn&AQI.Comparison.Switch=true&AQI.Comparison.Source=Local&Map.AQI=false&APIs.WeatherOL.HTTPHeaders={'Content-Type':'application/json'}&APIs.ColorfulClouds.HTTPHeaders={'Content-Type':'application/json'}&APIs.ColorfulClouds.Token=&APIs.ColorfulClouds.ForceCNForAQI=true&APIs.ColorfulClouds.ForceCNForComparison=false&APIs.WAQI.HTTPHeaders={'Content-Type':'application/json'}&APIs.WAQI.Token=&APIs.WAQI.Mode=Location
```

**更新日志：**
1. 支持Apple APIv3（即正在测试中的iOS 16、iPadOS 16和macOS Ventura）
2. 支持本地换算AQI标准
3. 支持对比昨日空气质量状况（本地缓存或彩云天气的历史数据）
4. 对降水强度的判断更加精确
5. 修复了降水即将开始却显示为降水即将停止的bug
6. 气象在线不再实时更新降水数据，脚本会自动筛选过期数据

**已知问题：**
1. （下小时降水）如果只能从API得到一个数据，脚本可能会超时崩溃
2. 本地换算的AQI虽然使用了WAQI算法，但是与WAQI略有差距
3. 气象在线和彩云天气作为AQI数据源时，logo无法正常显示
4. WAQI的模式切换功能不起作用
5. 仍不支持修改空气质量地图、一小时预报降水地图
6. （开发者）JSDoc的类型注释不完善
7. （开发者）Debug设置没有作用

**Comment by young61308** [comment]
作者辛苦了，请问有qx直接安装的链接么？

**Comment by WordlessEcho** [comment]
@young61308 链接已经放在上面了

**Comment by o1xhack** [comment]
@WordlessEcho surge安装了beta模块 boxjs安装了beta模块开启 但是还是使用的CN数据
![Uploading B15FC48D-1448-47F5-8F8D-8415087B990C.png…]()

**Comment by o1xhack** [comment]
@WordlessEcho  surge安装了beta模块 boxjs安装了beta模块开启 但是还是使用的CN数据
![9D844B7C-410A-4DAE-BC77-DF0747481BFC](https://user-images.githubusercontent.com/10677990/181916461-52b8192b-d6e9-46ed-91ba-571749052783.png)

**Comment by WordlessEcho** [comment]
> @WordlessEcho surge安装了beta模块 boxjs安装了beta模块开启 但是还是使用的CN数据
> ![9D844B7C-410A-4DAE-BC77-DF0747481BFC](https://user-images.githubusercontent.com/10677990/181916461-52b8192b-d6e9-46ed-91ba-571749052783.png)

@o1xhack 设置截全，贴日志

**Comment by WordlessEcho** [comment]
v4版天气模块进入RC版本，如果没有问题将推送为稳定版，请各位用户反馈

**Comment by easonnnone** [comment]
我这边boxjs配合订阅使用（Surge），天气App刷不出数据

**Comment by bryanwongxin** [comment]
beta5貌似失效了？

**Comment by WordlessEcho** [comment]
> beta5貌似失效了？

对的，iOS 16 developer beta 5上的天气不再允许用户MitM了

**Comment by trulynb** [comment]
> > beta5貌似失效了？
> 
> 对的，iOS 16 developer beta 5上的天气不再允许用户MitM了

那咋整

**Comment by WordlessEcho** [comment]
> > > beta5貌似失效了？
> > 
> > 
> > 对的，iOS 16 developer beta 5上的天气不再允许用户MitM了
> 
> 那咋整

去苹果上班

**Comment by bryanwongxin** [comment]
> > beta5貌似失效了？
> 
> 对的，iOS 16 developer beta 5上的天气不再允许用户MitM了

希望是个bug 下个版本能回来。。。

**Comment by WordlessEcho** [comment]
别抱什么希望了，不可能是bug

**Comment by jqyisbest** [comment]
沃日，这搞得我都不想买IP14了....一个天气应用还校验证书，有点恶心

**Comment by cikichen** [comment]
iOS 16更新了，天气拉不到数据
