### ISSUE TITLE
apple tv en链接失效

### ISSUE THREAD

**Issue by bryanwongxin** [VirgilClyne/iRingo#109]
https://github.com/VirgilClyne/iRingo/blob/main/sgmodule/Apple_TV_EN.sgmodule?raw=true

404了…

**Comment by VirgilClyne** [comment]
你都来github了，就不舍得看看wiki的新版本么🤔

**Comment by bryanwongxin** [comment]
> 你都来github了，就不舍得看看wiki的新版本么🤔

不好意思啊 玩不太来 全靠摸索🤣

**Comment by VirgilClyne** [comment]
> > 你都来github了，就不舍得看看wiki的新版本么🤔
> 
> 不好意思啊 玩不太来 全靠摸索🤣

https://github.com/VirgilClyne/iRingo/wiki/📺TV-app
