### ISSUE TITLE
使用定位服务后天气APP偶发不能定位

### ISSUE THREAD

**Issue by SingSky** [VirgilClyne/iRingo#116]
## 使用环境
iOS 15.5，Quantumult X 1.0.29-678，iRingo Location最新版（V2版，一键安装），BoxJS对应脚本订阅最新版（测试前已更新）

## 问题描述

后台开启 Quantumult X 代理服务，保持正常网络连接。
点击进入天气APP，发现“当前位置”的天气无法更新，显示空白，如下图。
<p align="center">
<a href="https://sm.ms/image/brRQxBzjDnqsWfA" target="_blank"><img src="https://s2.loli.net/2022/07/01/brRQxBzjDnqsWfA.png" width="200" ></a>
</p>
于此同时，“已添加到位置列表”的城市可正常更新和显示。
点击左下角地图按钮，手动选择右上角定位，则定位到南大西洋某片海域，如下图。
<p align="center">
<a href="https://sm.ms/image/brRQxBzjDnqsWfA" target="_blank"><img src="https://s2.loli.net/2022/07/01/6aYnyKCU3GM9zNE.png" width="200" ></a>
<a href="https://sm.ms/image/brRQxBzjDnqsWfA" target="_blank"><img src="https://s2.loli.net/2022/07/01/GWiTHCqj9Be8Zr7.png" width="200" ></a>
</p>

此时Quantumult X中最近一次的脚本记录输出为：

```
状态:		已释放
网络请求:	无
描述:		 	
❚  script-request-header
❚  https://gsp-ssl.ls.apple.com/dispatcher.arpc
❚  ^https?:\/\/gsp-ssl\.ls\.apple\.com\/dispatcher\.arpc$
❚  https://raw.githubusercontent.com/VirgilClyne/iRingo/main/js/Location.request.js
日志:		 	
❚  🔔Apple Location Services v2.10.0-request, 开始!
❚  ⚠ Apple Location Services v2.10.0-request, Set Environment Variables
❚  🎉 Apple Location Services v2.10.0-request, Set Environment Variables
Settings: object
Settings内容: {"Switch":true,"PEP":{"GCC":"US"},"Geo_manifest":{"Dynamic":{"Config":{"Country_code":"US"}}},"Services":{"Dispatcher":"CN","Directions":"CN","Traffic":"AUTO","Tiles":"AUTO"},"Config":{"Announcements":{"Environment":"prod"},"Defaults":{"LagunaBeach":true,"DrivingMultiWaypointRoutesEnabled":true,"GEOAddressCorrection":true,"LookupMaxParametersCount":true,"LocalitiesAndLandmarks":true,"PedestrianAR":true,"6694982d2b14e95815e44e970235e230":true,"OpticalHeading":true,"UseCLPedestrianMapMatchedLocations":true}}}
❚  dispatcher.arpc
❚  🔔Apple Location Services v2.10.0-request, 结束! 🕛 0.018 秒
```

（后续没有Apple Weather的执行记录）

如日志内容所示，BoxJS设置为：

<p align="center">
<a href="https://sm.ms/image/8wFNQfoOGhL5UWj" target="_blank"><img src="https://s2.loli.net/2022/07/01/FzqsQZP3yL4EKdG.png" width="200"></a>
</p>

下方选项全部开启。

同时，最近的网络活动显示 对 `weather-analytics-events.apple.com` 的访问

<p align="center">
<a href="https://sm.ms/image/8wFNQfoOGhL5UWj" target="_blank"><img src="https://s2.loli.net/2022/07/01/8wFNQfoOGhL5UWj.png" width="200"></a>
</p>

对 `gsp-ssl.ls.apple.com` 的访问

<p align="center">
<a href="https://sm.ms/image/8wFNQfoOGhL5UWj" target="_blank"><img src="https://s2.loli.net/2022/07/01/DpSxzsWEIoJyh2M.png" width="200"></a>
</p>

对 `gspe19-ssl.ls.apple.com` 的访问（数字19为随机值）

<p align="center">
<a href="https://sm.ms/image/8wFNQfoOGhL5UWj" target="_blank"><img src="https://s2.loli.net/2022/07/01/oYc8F9BEQ73gn4a.png" width="200"></a>
</p>

## 期望看到的结果

天气APP正常定位

## 目前采用的解决方案

在BoxJS中临时关闭“定位服务”的“总功能开关”，保存后再次进入天气APP刷新，即可看到正常天气信息。

此时的脚本记录输出为：

Location：

```
状态:		已释放
网络请求:	无
描述:		 	
❚  script-request-header
❚  https://gsp-ssl.ls.apple.com/dispatcher.arpc
❚  ^https?:\/\/gsp-ssl\.ls\.apple\.com\/dispatcher\.arpc$
❚  https://raw.githubusercontent.com/VirgilClyne/iRingo/main/js/Location.request.js
日志:		 	
❚  🔔Apple Location Services v2.10.2-request, 开始!
❚  ⚠ Apple Location Services v2.10.2-request, Set Environment Variables
❚  🎉 Apple Location Services v2.10.2-request, Set Environment Variables
Settings: object
Settings内容: {"Switch":false,"PEP":{"GCC":"US"},"Services":{"Dispatcher":"CN","Directions":"CN","Traffic":"AUTO","Tiles":"AUTO"},"Geo_manifest":{"Dynamic":{"Config":{"Country_code":"US"}}},"Config":{"Announcements":{"Environment":"prod"},"Defaults":{"LagunaBeach":true,"DrivingMultiWaypointRoutesEnabled":true,"GEOAddressCorrection":true,"LookupMaxParametersCount":true,"LocalitiesAndLandmarks":true,"PedestrianAR":true,"6694982d2b14e95815e44e970235e230":true,"OpticalHeading":true,"UseCLPedestrianMapMatchedLocations":true}}}
❚  🔔Apple Location Services v2.10.2-request, 结束! 🕛 0.02 秒

```

Apple Weather：

```
状态:		已释放
网络请求:	无
描述:		 	
❚  script-response-body
❚  https://weather-data.apple.com/v2/availability/33.203/114.604
❚  ^https?:\/\/weather-data\.apple\.com\/(v1|v2)\/availability\/.*
❚  https://raw.githubusercontent.com/VirgilClyne/iRingo/main/js/Weather.Availability.js
日志:		 	
❚  🔔Apple Weather Availability v1.0.2, 开始!
❚  ⚠ Apple Weather Availability v1.0.2, Set Environment Variables
❚  🎉 Apple Weather Availability v1.0.2, Set Environment Variables
Settings: object
Settings内容: {"Switch":true,"NextHour":{"Switch":true},"AQI":{"Switch":true,"Mode":"WAQI Public","Location":"Station","Auth":null,"Scale":"EPA_NowCast.2204"},"Map":{"AQI":false}}
❚  🎉 Apple Weather Availability v1.0.2, 可用性检查
❚  200
❚  🎉 Apple Weather Availability v1.0.2, 功能列表
["currentWeather","forecastDaily","forecastHourly","history","weatherChange","severeWeather","forecastNextHour","airQuality"]
❚  🔔Apple Weather Availability v1.0.2, 结束! 🕛 0.023 秒

```

网络活动中可以看到对 `weather-analytics-events.apple.com`  `gsp-ssl.ls.apple.com`  `weather-data.apple.com`   `api.waqi.info`   `www.weatherol.cn` 的访问

不同之处在，访问`gsp-ssl.ls.apple.com`的“状态”由原先的`socket closed by remote peer`变为"已关闭"和"连接重用到419530"

之后再次开启开关即可。但一段时间后又会出现上述现象。

**Comment by SingSky** [comment]
> 让我理解一下，你打开了定位模块之后，就无法看见任何`weather-data.apple.com`的请求了是吗？

是的，在出现白屏的时候是这样， 同时也看不到 iRingo for Apple Weather 的执行记录。

但如果使用上面提到的临时解决方案，天气信息就恢复正常了（但此时Map也回落到了高德地图）。看到正常的天气信息之后再打开定位模块，就可以在有限时间（大概1~2天）内，正常刷新并查看天气，App内定位也是准确的，直到白屏再次出现。

看起来像是天气App在获取位置时遇到了奇怪的问题。

**Comment by VirgilClyne** [comment]
wiki里早已说明
Quantumult X 无法指定“调度器”“导航”“交通状况”“瓦片地图”的服务版本

**Comment by VirgilClyne** [comment]
从你发图的症状来看
QX对链接url的重定向修改没有生效
修改后依旧为国际版服务的endpoint

但是对于请求头Host的字段修改却生效了
最终导致url与host不符，链接建立失败

只要你把调度器和导航的服务改为AUTO应该就正常了

因为我所有平台共用相同的脚本
其他平台并未见此问题，所以判断为应该是QX的bug或特性

**Comment by SingSky** [comment]
感谢帮助！我误会了“无法指定服务版本”的含义，以为结果会是无论如何选择都不会生效，没有意识到会有url和host的冲突。
