### ISSUE TITLE
天气模块 GetData:Nearest执行失败

### ISSUE THREAD

**Issue by eli9966** [VirgilClyne/iRingo#117]
ios15.5 天气模块3.2.x
![image](https://user-images.githubusercontent.com/94114651/176994418-89eb3459-e408-4358-85d7-b0abdfb1ead1.png)

**Comment by WordlessEcho** [comment]
一般都是网络问题，可尝试将 api.waqi.info 加入代理规则

**Comment by WordlessEcho** [comment]
长时间未有回复，关闭本issue
Close due to no response.
