### ISSUE TITLE
是否能在未来给BosJS新增一个直连的总开关？

### ISSUE THREAD

**Issue by new88888** [VirgilClyne/iRingo#125]
RT，在家的时候已经用路由器走clash了，所以就没有必要再走两遍节点，但是似乎插件的策略组就默认把对应的hostname给加上去了。想做到在家时候 设备端只走插件 交给路由器端走节点（目前路由器已经手动添加所有相关的hostname），然后在外面的时候，设备再走节点。

当然也许这可能是我个人对于Loon还是不太熟悉？我尝试只给Loon添加一个直连的本地节点，插件最终也是无法生效的。

**Comment by WordlessEcho** [comment]
这是一个和代理软件相关的问题，与Box.js和iRingo都无关，请咨询代理软件支持
