### ISSUE TITLE
ios 16 beta5天气使用复写后无法获取数据

### ISSUE THREAD

**Issue by Toyro7356** [VirgilClyne/iRingo#127]
仅weather-data.apple.com在网络活动中mitm fail，关闭天气复写恢复正常。

**Comment by trulynb** [comment]
天气app从beta5开始不能mitm了

**Comment by DaBo0219** [comment]
在qx中关闭复习 jsbox里打开 不行 在jsbox里关闭qx里打开也不行。在天气里不能显示温度
![Uploading B06E629E-2A16-4446-BE3E-AE1762C4E6EC.png…]()

**Comment by luckyreny** [comment]
IOS16正式版，天气在网络活动中mitm fail，关闭天气复写恢复正常。
