### ISSUE TITLE
新闻都到不了这一步，被限制了

### ISSUE THREAD

**Issue by luckyreny** [VirgilClyne/iRingo#132]
![3b198133a1f48b12e727c71bfa748dd](https://user-images.githubusercontent.com/9688468/187595647-f8e3f8ef-a4fb-4d1d-84b0-db3141b1b726.jpg)
![5ce2cfccc2042d385f6047dcd6b4987](https://user-images.githubusercontent.com/9688468/187595670-8c28f871-922e-41fd-9c02-d3c5cd9440cd.jpg)

**Comment by bunizao** [comment]
您好 请尝试在 `设置` `语言与地区`中将地区改为美国/英国/澳大利亚/加拿大。
