### ISSUE TITLE
请问为什么api.smoot.apple.com直接被关闭了呢。ios16  v2版本，无其他模块，飞行模式

### ISSUE THREAD

**Issue by tf14132** [VirgilClyne/iRingo#135]

**Comment by Algar233** [comment]
假如你已升级到 iOS 16，且在此之前一直在使用 Apple Weather 相关脚本/插件

那么此时你打开 Apple Weather 会发现一直加载不出数据。如图。

此时那么你只有删除 Apple Weather 相关插件，并重新启动代理 app。或者降级回 iOS 15。

因为在 iOS 16 已禁止 MitM Apple Weather 相关地址。只能期待 Apple 在未来会放开限制。

**Comment by tf14132** [comment]
是Siri模块，无其他
