### ISSUE TITLE
iOS 16重寫失敗了

### ISSUE THREAD

**Issue by yiiyahui** [VirgilClyne/iRingo#136]
天氣重寫失敗。App直接不顯示了

**Comment by shindgewongxj** [comment]
是这样的，由于相关操作可能会影响到Apple官方对Weather Kit的期望，所以其从证书方面被禁止了。目前没有很好的解决方案，只能通过禁用模块实现天气的基础功能，望谅解。

**Comment by yiiyahui** [comment]
> 是这样的，由于相关操作可能会影响到Apple官方对Weather Kit的期望，所以其从证书方面被禁止了。目前没有很好的解决方案，只能通过禁用模块实现天气的基础功能，望谅解。
> 
> 另外，可关注[电报频道](https://t.me/GetSomeFriesChannel)获取最新消息。

感謝回覆。

**Comment by VirgilClyne** [comment]
#137

**Comment by VirgilClyne** [comment]
https://github.com/VirgilClyne/iRingo/issues/137
