### ISSUE TITLE
Quan X打开weather脚本重写后，weather-data.apple.com:443 为NA

### ISSUE THREAD

**Issue by Youmio** [VirgilClyne/iRingo#137]
weather-data.apple.com:443 为NA

网络活动- JS中没有weather相关记录
![IMG_2EA65109E3EE-1](https://user-images.githubusercontent.com/36833961/190850397-f87a2baa-752b-4eae-8b2a-4a482a80ce7c.jpeg)
![IMG_3704](https://user-images.githubusercontent.com/36833961/190850424-70af5806-9028-4a41-a57a-31004bfea236.PNG)

**Comment by Youmio** [comment]
打开weather脚本后，天气内容显示不出来

**Comment by Youmio** [comment]
关闭weather脚本之后，weather-data.apple.com:443能正常连接

**Comment by Aldof-hub** [comment]
ios15.7也出现了和你一样的情况

**Comment by HaloWww** [comment]
一样的问题 ios15.1.1

**Comment by terencehyz** [comment]
iOS 15.7 出现同样问题

**Comment by cjjdaq** [comment]
同样如此

**Comment by VirgilClyne** [comment]
苹果已通过远程配置下发对`weather-data.apple.com`做了证书固定
已无法再通过MitM插入自定义的天气数据
[天气](https://github.com/VirgilClyne/iRingo/wiki/🌤-天气)部分项目已终止
受灾范围：最近两个版本的`iOS`,`macOS`,`ipadOS`,`watchOS`系统
