### ISSUE TITLE
watch ultra寻路者表盘经纬度显示

### ISSUE THREAD

**Issue by Melon999** [VirgilClyne/iRingo#138]
手表证书信任
开启定位服务后，iPhone指南针、watch指南针内经纬度均显示正常

定位地区、手机系统地区设置为美国（地区为大陆寻路者经纬度表盘会被屏蔽）

表盘经纬度一直显示正在更新，希望能得到更新支持

![incoming-D33EECBF-5FD9-4709-AFDE-6E919306B3F5](https://user-images.githubusercontent.com/58394955/192729944-76383d83-f94c-4001-88ad-37b8e2389a5f.PNG)

**Comment by Arthmas0124** [comment]
同求！用iRingo就是想激活这个表盘。手机上都可以了手表还不行。

**Comment by chk970222** [comment]
> 同求！用iRingo就是想激活这个表盘。手机上都可以了手表还不行。

请问，手机上怎么操作的？我一直不行

**Comment by Arthmas0124** [comment]
你到哪步不行了？

**Comment by chk970222** [comment]
我开了重写，然后飞行模式然后地图始终没有变就一直不行。地区也选的非大陆，语言倒是简体。谢谢

**Comment by VirgilClyne** [comment]
刚刚分离了watchOS和其他设备的定位服务设置，可以手机高德地图的情况下，手表保持指南针经纬度了
模块脚本和boxjs订阅都要更新
但是我没有ultra，所以不知道对新的寻路者表盘的经纬度是否有效，请配合测试

**Comment by Arthmas0124** [comment]
好，我现在就搞

**Comment by Melon999** [comment]
我在等换货到，辛苦了

**Comment by Arthmas0124** [comment]
支持了！手表可以显示了
![Uploading 65FDCA91-A7A8-4EA7-A928-25342E9D54AB.png…]()

**Comment by Arthmas0124** [comment]
手表可以显示经纬度了！
![awu](https://user-images.githubusercontent.com/114609687/194701870-ec55ba7a-729e-47d2-8971-5e50c7ca1834.jpeg)

**Comment by Arthmas0124** [comment]
感谢！经纬度可以显示了！
![WechatIMG283](https://user-images.githubusercontent.com/114609687/194701955-53dfb3dc-b3e9-499d-b638-6efbc16bec19.jpeg)

**Comment by Melon999** [comment]
> 感谢！经纬度可以显示了！
> 
> ![WechatIMG283](https://user-images.githubusercontent.com/114609687/194701955-53dfb3dc-b3e9-499d-b638-6efbc16bec19.jpeg)
> 
> 

兄弟9.0.2可以吗，我新的现在指南针正常，表盘不显示，确认下是不是系统问题

**Comment by Melon999** [comment]
那个watch页面选哪个都是无数据正常吗，我用的surge，你用的quanx吗
都更新过了，证书也装了，重启过了，指南针里面经纬度是好的，只有表盘不行，麻了

Arthmas0124 ***@***.***>于2022年10月13日 周四23:02写道：

**Comment by Arthmas0124** [comment]
watch页面是 一个动态配置， 一个通告配置啊..我用的shadowrocket，loon也可以。

**Comment by chk970222** [comment]
弟兄，江湖救个急，我好不容易把经纬度搞出来了，手机上显示正常度分秒，但是手表上却显示48R XT 坐标，这个搞不明白，能不能把你boxjs相关设置截个图参考一下，谢谢，或者手表上有什么特殊设置？

**Comment by chk970222** [comment]
谢谢

**Comment by chk970222** [comment]
离开手机又会不显示

**Comment by Melon999** [comment]
> 离开手机又会不显示

没手机当然不行啊，要mitm的
我的指南针里经纬度是正常更新的证明手表已经被mitm了，但是表盘的经纬度就是一直显示正在更新
所以我想知道你们都咋设置的，手机手表地区和两个boxjs设置

**Comment by chk970222** [comment]
手机搞好以后，重启手表就好了，我是重启的，昨天搞出来以后丢了三次，三次都重启的

Melon999 ***@***.***>于2022年10月16日 周日01:19写道：

**Comment by AdoShan** [comment]
请问一下手表咋装证书

**Comment by laosh1** [comment]
> 请问一下手表咋装证书

还是在安装手机证书界面进行安装，会有一个提示，问你是给iPhone 还是 Apple Watch 安装。
