### ISSUE TITLE
从Loon里安装Boxjs时提示错误的url

### ISSUE THREAD

**Issue by williamjiwl** [VirgilClyne/iRingo#142]
各位大佬，我点文章里的安装链接，然后跳转到Loon里之后提示说错误的url，无法装Boxjs…请问下这是啥情况？是我设置哪里有问题吗？谢谢大家！

![image](https://user-images.githubusercontent.com/96057006/196101624-5464a837-bc44-4924-9220-72ee78a37799.png)

**Comment by gyzhuang-autox** [comment]
me too. Why??
