### ISSUE TITLE
iPhone更新了IOS16.1，手表更新了watch OS9.1后，表盘的经纬不显示了

### ISSUE THREAD

**Issue by aliwanggg** [VirgilClyne/iRingo#143]
QuanX 用boxjs开了定位服务和WATCH服务，更新前可以更新后就不显示了，飞行模式下重新安装了证书和重定位了也还是不行，手机指南针显示经纬正常，就手表表盘不显示了，手机指南针正常显示。大佬帮忙分析下是什么原因啊，纯小白，按教程一步一步来操作的😂

更新前的表盘可显示
![751183BB-7828-4168-8B4A-B9A3078EB9B5](https://user-images.githubusercontent.com/55615696/198039618-bb010b1f-d37e-413e-8c03-9ebbb54c6a9e.jpeg)

更新后就没了
![2BAFDC3E-F219-46B1-A4EA-4A2956DBEB3F](https://user-images.githubusercontent.com/55615696/198039648-8b043d63-3d70-4e85-8541-3a91a428f504.jpeg)

**Comment by VirgilClyne** [comment]
watchOS 9.1起，国家与地区为“中国”时，“寻路者表盘”无经纬度显示
