### ISSUE TITLE
「Siri与搜索」功能 Bug Report

### ISSUE THREAD

**Issue by farmostream** [VirgilClyne/iRingo#145]
在成功开启 Siri与搜索并关闭定位服务后，可以正常使用。
但是只要再进一次「地图」应用，Siri搜索就会指向https://api.smoot.apple.cn，「Siri与搜索」服务也就随之失效了。

**Comment by shindgewongxj** [comment]
请保持iRingo位置服务模块开启，其并不会对其他服务及日常使用带来任何负面影响。

**Comment by farmostream** [comment]
> 请保持iRingo位置服务模块开启，其并不会对其他服务及日常使用带来任何负面影响。

谢谢回复。刚试了下，保持定位服务开启，只要再进一次「地图」应用，「Siri与搜索」服务还是会失效。

**Comment by shindgewongxj** [comment]
如模块失效，请尝试严格重复激活步骤。

**Comment by farmostream** [comment]
> 如模块失效，请尝试严格重复激活步骤。

已严格重复5次标准（首次）激活流程，看起来还是会失效。

**Comment by idjfia** [comment]
同严格遵守激活步骤，但仍然失效

**Comment by yewild** [comment]
> 如模块失效，请尝试严格重复激活步骤。

我的是iPhone 确实是这样 我猜测应该是插了电话卡 如果重新打开地图会触发地区检测 导致失效 我的是小火箭 其他代理软件未知

**Comment by VirgilClyne** [comment]
需要启用`重写`、`脚本`、`MitM`功能

否则代理软件无能力改写连接请求
