### ISSUE TITLE
4月28日后更新脚本之后qx的siri模块失效，小火箭无问题

### ISSUE THREAD

**Issue by meme-lau** [VirgilClyne/iRingo#165]
作者你好，最近自动更新了你qx的siri模块和定位模块后，qx下siri搜索结果，浏览器查询结果没生效，qx版本1.3.0。iOS16.4.1。小火箭是OK的。已重复多次按照作者给的步骤来开始，验证了两天，都不行，这期间qx版本配置均没更新过。
我怀疑是重写的时候，应用拿到结果有延迟，我拿Safari测试访问了https://gspe1-ssl.ls.apple.com/pep/gcc，qx响应结果非常慢，小火箭就不存在延迟。

**Comment by VirgilClyne** [comment]
已修复

**Comment by meme-lau** [comment]
666，回去试试看
