### ISSUE TITLE
用国外地图数据配高德导航数据好像地图偏移的厉害

### ISSUE THREAD

**Issue by Zcx5200** [VirgilClyne/iRingo#167]
基本上可以说直接搜索出来的地方都是要偏离实际地点的😓

**Comment by Zcx5200** [comment]
完全没解决…我觉得这个在国内应该是很难解决所以我就关闭了

**Comment by VirgilClyne** [comment]
https://zh.wikipedia.org/wiki/中华人民共和国地理数据限制
