### ISSUE TITLE
boxjs更新到0.12.9后，苹果地图数据无法显示tomtom数据

### ISSUE THREAD

**Issue by lirob** [VirgilClyne/iRingo#169]
问题已解决

**Comment by yewild** [comment]
> 问题已解决

请问你是用Siri模块时会不会出现这种情况 开启飞行模式 打开地图可以正常使用 关闭飞行模式可以正常使用 但是重新打开地图 就失效了

**Comment by lirob** [comment]
恢复设置以后就没有问题了。感谢大佬的关注与支持。

yewild ***@***.***>于2023年5月24日 周三下午8:33写道：
