### ISSUE TITLE
词典显示问题

### ISSUE THREAD

**Issue by HoTszHo** [VirgilClyne/iRingo#170]
![IMG_0057](https://github.com/VirgilClyne/iRingo/assets/68243996/171dcd0c-a827-444e-9463-1dd7e5cfbd2e)
![IMG_0058](https://github.com/VirgilClyne/iRingo/assets/68243996/2f69b0aa-053c-44ee-af88-b270db0c1f50)
会出现上面这种情况，点进去就是不可用，词典也对不上，设置里取消这本词典也没用

**Comment by HoTszHo** [comment]
这个情况好像ios17也会出现，词典是第一项推荐而且完全无法展开，比ios16的情况更恶劣

**Comment by VirgilClyne** [comment]
> 这个情况好像ios17也会出现，词典是第一项推荐而且完全无法展开，比ios16的情况更恶劣

词典的配置下发有一个单独的链接，有空我会处理一下的

**Comment by HoTszHo** [comment]
> > 这个情况好像ios17也会出现，词典是第一项推荐而且完全无法展开，比ios16的情况更恶劣
> 
> 
> 
> 词典的配置下发有一个单独的链接，有空我会处理一下的

17正式版出了，麻烦处理🙏🏻

**Comment by AkinoYuiko** [comment]
@VirgilClyne 大佬什么时候有空处理一下词典这个呢？十分感谢！

**Comment by VirgilClyne** [comment]
fixed

**Comment by HoTszHo** [comment]
> fixed

输入单词后回车仍会出现这种情况，不回车推荐的词典也是现实中文辞典但是里面是英文
