### ISSUE TITLE
期待Apple Music外区中文

### ISSUE THREAD

**Issue by rollingshmily** [VirgilClyne/iRingo#173]
大佬，有无计划对Apple Music下手，目前用的土区am，有一个小小的问题，外区的很多中文歌都用的英文名，事实上在国区/美区它是有中文名的，不知道是不是只有土区这样👀

**Comment by Sponge-bink** [comment]
美区的日文歌也都是罗马音，尽管日区是日文原文，

> 不知道是不是只有土区这样

所以我觉得不是。

**Comment by x6ufeng** [comment]
https://developer.apple.com/help/app-store-connect/reference/app-store-localizations/
这其实是个本地化问题...

**Comment by Humite0** [comment]
Same issues here. Singers and songs from HK are displayed as English. Technically is this possible to hack with iRingo? @

**Comment by jjaychen1e** [comment]
Same issues here. Singers and songs from HK are displayed as English. Technically is this possible to hack with iRingo? @VirgilClyne
