### ISSUE TITLE
ios 17 surge 关闭飞行模式后模块失效

### ISSUE THREAD

**Issue by J02Octo** [VirgilClyne/iRingo#175]
目前使用ios17 beta 3 ，软件使用Surge 5，在开启飞行模式的时候，定位模块正常，siri建议也能正常使用，但是当断开飞行模式之后不久siri建议就会时效。
目前已经尝试过重启，重新配制，在模块生效后关闭/开启定位模块，都会出现该问题。

**Comment by VirgilClyne** [comment]
需要启用重写、脚本、MitM功能

**Comment by chouynacy** [comment]
> 需要启用重写、脚本、MitM功能 请问有脚本链接吗

**Comment by aadenyihongchen** [comment]
在iOS17 RC版，同样使用Surge 5，重写、脚本、MitM功能已启用，也是一样的情况：开启飞行模式有效，关闭飞行模式失效，再开启飞行模式又有效。

**Comment by J02Octo** [comment]
> 需要启用重写、脚本、MitM功能

玄学问题，后来更新了版本之后该问题没有再出现
