### ISSUE TITLE
能否只开启Siri和搜索，不用定位服务，地图app继续使用高德

### ISSUE THREAD

**Issue by azir12345** [VirgilClyne/iRingo#179]
如果只是将gspe1-ssl.ls.apple.com强制直连的话就无法使用搜索，如果将上述网址设置为代理的时候搜索就可以正常使用。如果地图左下角没有高德地图图案的话，导航完全用不了，此时可以用高级Siri和搜索。可否让高德地图字样还在（或者字样消失但仍可以导航）的同时使用高级版Siri和搜索

**Comment by lSquIrRel1031** [comment]
![IMG_8466](https://github.com/VirgilClyne/iRingo/assets/79552818/9c1f503a-c2e9-4192-9ada-058d805b800f)
在boxJS里改成这样就行

**Comment by azir12345** [comment]
我改成这样以后还是不行，导航直接没法用，地图是tomtom的地图，是因为我是小火箭的问题吗
