### ISSUE TITLE
启用Siri搜索后搜索英文单词时词典card跳转现代汉语词典

### ISSUE THREAD

**Issue by AkinoYuiko** [VirgilClyne/iRingo#187]
词典里已启用牛津英汉汉英词典、现代汉语词典、New Oxford American Dictionary。
如标题所述，搜索一个英文单词时，在search页面会显示该单词的英文解释，但是跳转是现代汉语词典，点进去会因为没有这个条目而提示“内容不可用”
例如：搜索“angry”
以上似乎是部分词语才会出现这种现象，尚没有对比测试是否是Siri搜索模块导致，后续跟进测试一下

**Comment by VirgilClyne** [comment]
fixed
