### ISSUE TITLE
iOS 17.4.1下已失效

### ISSUE THREAD

**Issue by Nuuuk** [VirgilClyne/iRingo#202]
指南针无法显示经纬度，关闭飞行模式后打开地图提示：Current location not available.

**Comment by ddrr2008** [comment]
![IMG_3081](https://github.com/VirgilClyne/iRingo/assets/112458804/e99305e3-98c8-4eb6-b7f6-1988132f9ab6)

Ios17.4.1  开启飞行模式，siri建议和指南针经纬度可用，关闭飞行模式后siri建议和指南针经纬度不可用。但相册中的look up 可以识别动物和花草功能。

**Comment by Nuuuk** [comment]
我的飞行模式下也不显示经纬度。

**Comment by xingjiu29** [comment]
> 我的飞行模式下也不显示经纬度。

我也是

**Comment by ddrr2008** [comment]
> > 我的飞行模式下也不显示经纬度。
> 
> 我也是

Iringo 已经更新，很好的解决上面的问题，你也去更新 Quantumult x的重写和boxjs的定阅，重新体验

**Comment by ddrr2008** [comment]
> > > > 我的飞行模式下也不显示经纬度。
> > > 
> > > 
> > > 我也是
> > 
> > 
> > Iringo 已经更新，很好的解决上面的问题，你也去更新 Quantumult x的重写和boxjs的定阅，重新体验
> 
> 并不行，更新了也一样，过段时间就会掉，1-6个小时之间

能否提供一下你的配置截图，我一直使用正常

**Comment by Nuuuk** [comment]
你是iPhone几？什么版本iOS？我15，17.4.1，无论如何折腾都不行了，一关飞行模式就失效，明显检测SIM卡了。

**Comment by VirgilClyne** [comment]
https://t.me/GetSomeFriesChannel/299
