### ISSUE TITLE
新版本的定位服务会过段时间自动就不行，怎么解决？之前的版本一直都可以保持的

### ISSUE THREAD

**Issue by Devilyjn** [VirgilClyne/iRingo#205]
就是已经开启了定位了，指南针可以显示经纬度，地图也是外区的，但是过一两个小时就会失效了，怎么解决？大佬们

**Comment by LevineWoo** [comment]
不知道是不是我设置有问题，国内国内的地图数据并不能很好切换。不能看国内地图时用高德，看国外地图时用tomtom的

**Comment by Nuuuk** [comment]
我的一关闭飞行模式就不行了。

**Comment by mrbillxp** [comment]
好像在最新版系統，iOS / iPadOS 會同時檢測你的 SIM 卡歸屬地，信號來源地，定位數據。

**Comment by Nuuuk** [comment]
跟TikTok一样流氓了。以后不买国行iPhone了。

**Comment by Phinsin666** [comment]
同样的问题，刚开始指南针还是有经纬度，过了一段时间重新打开就没了。

**Comment by Fau818** [comment]
得保持苹果的服务都走US的节点; 否则开着飞行我都失效

**Comment by Devilyjn** [comment]
> 得保持苹果的服务都走US的节点; 否则开着飞行我都失效

这样可以吗？需要这样？

**Comment by Fau818** [comment]
> > 得保持苹果的服务都走US的节点; 否则开着飞行我都失效
> 
> 这样可以吗？需要这样？

我今天测试下来是这样的, 版本是 17.4.1

**Comment by Devilyjn** [comment]
> > > 得保持苹果的服务都走US的节点; 否则开着飞行我都失效
> > 
> > 
> > 这样可以吗？需要这样？
> 
> 我今天测试下来是这样的, 版本是 17.4.1

我试了全部走美国节点也是一样的

**Comment by VirgilClyne** [comment]
https://t.me/GetSomeFriesChannel/299
