### ISSUE TITLE
成功开启后 Spotlight 词典出现问题

### ISSUE THREAD

**Issue by NLasagna** [VirgilClyne/iRingo#208]
![IMG_1529](https://github.com/VirgilClyne/iRingo/assets/20740276/cfce4cd5-00cc-4f1c-923a-6c2478eb4da7)
![IMG_1530](https://github.com/VirgilClyne/iRingo/assets/20740276/dff51de7-ffcf-4962-963e-223ba2d66f77)
![IMG_1531](https://github.com/VirgilClyne/iRingo/assets/20740276/74589b85-aec3-4124-9db7-983d3c1d1f41)

在完全版的spotlight里似乎只有英文的词典，并且如图所示，显示内容不可用，全局代理后仍不可用。

**Comment by VirgilClyne** [comment]
fixed

**Comment by NLasagna** [comment]
未见解决。
