### ISSUE TITLE
更新15.1后Apple News无法连接服务器

### ISSUE THREAD

**Issue by Meonthb** [VirgilClyne/iRingo#21]
![](https://i.imgur.com/y2QthAs.png)

并且有SIM卡的设备在关闭飞行模式后siri knowledge失效

**Comment by Meonthb** [comment]
目前即使是无sim卡的iPad也无法显示news，只有Mac news主页可用，小组件显示未能载入报告。

**Comment by VirgilClyne** [comment]
> 目前即使是无sim卡的iPad也无法显示news，只有Mac news主页可用，小组件显示未能载入报告。

能提供小组件用到的域名地址吗🤔

**Comment by VirgilClyne** [comment]
Apple News模块已更新 可以试试看

**Comment by RasinGue** [comment]
试了一下，iphone飞行模式可用，接触飞行模式之后马上就 "story unavailable: Apple news isn't supported in your current region"

**Comment by VirgilClyne** [comment]
> 试了一下，iphone飞行模式可用，接触飞行模式之后马上就 "story unavailable: Apple news isn't supported in your current region"

一般少则坚持20分钟，多则坚持几小时，才会触发SIM卡检测，你一定不少app在后台获取定位吧🤪

**Comment by WordlessEcho** [comment]
Closed due to no replies for a long time.
长时间未答复，关闭issue。
