### ISSUE TITLE
iOS下地图缩小时有偏移，放大到街道大小时偏移消失

### ISSUE THREAD

**Issue by CooperLuo** [VirgilClyne/iRingo#212]
iOS下地图缩小时有偏移且无POI，放大到街道大小时偏移消失且出现POI。疑似不同比例尺下地图源不同。采用默认配置，无修改。

**Comment by VirgilClyne** [comment]
国内地区放大的地图为高德地图，缩小为国际版地图
其余地区无论大小均为国际版地图
默认混合的地图模式就是这样的
