### ISSUE TITLE
iOS18的spotlight搜索似乎失效了

### ISSUE THREAD

**Issue by mis0no** [VirgilClyne/iRingo#220]
前几个beta版本好像还能用，不知道是beta3还是4开始无论怎么切换开关和模块搜索功能都不能激活

**Comment by lge6** [comment]
macos sequoia beta 5也有同样的情况
<img width="1053" alt="image" src="https://github.com/user-attachments/assets/1e25234d-4b51-4c00-84b6-83edca823d39">

**Comment by lge6** [comment]
问题解决了，重新安装mitm证书，在macos和ios上都成功解锁siri功能
![Uploading IMG_5898.PNG…]()

**Comment by JinjaNatsume** [comment]
siri搜索的问题可以用beta版的模块
https://github.com/VirgilClyne/iRingo/raw/beta/sgmodule/Siri.V2.macOS.beta.sgmodule
https://github.com/VirgilClyne/iRingo/raw/beta/sgmodule/Siri.V2.beta.sgmodule

**Comment by mis0no** [comment]
> siri搜索的问题可以用beta版的模块
> 
> https://github.com/VirgilClyne/iRingo/raw/beta/sgmodule/Siri.V2.macOS.beta.sgmodule
> 
> https://github.com/VirgilClyne/iRingo/raw/beta/sgmodule/Siri.V2.beta.sgmodule

好像还是没有完全解决，开飞行模式可以生效。关掉飞行模式短时间内没问题，过段时间还是会失效

**Comment by Nudeladder** [comment]
有一个问题。我的mac上用的也是loon，但是loon是ios版本的，这就意味着无法使用mac版本的插件。
