### ISSUE TITLE
iOS 18.1 beta 启用最新Siri beta模块后出现的一些问题

### ISSUE THREAD

**Issue by PatrickScLau** [VirgilClyne/iRingo#221]
启用最新beta模块后，如果开启飞行模式，Siri建议、Visual Lookup等仍能正常使用，请求域名为api-glb-aapne1c.smoot.apple.com，此时Ask Siri请求将不会访问guzzoni.apple.com，Siri的回复也因此基于百度。
在进一步控制变量后测试发现：
关闭飞行模式，启用模块：Siri建议、Visual Lookup失效，请求域名为api.smoot.apple.com(/cn)，Ask Siri请求访问guzzoni.apple.com, Siri回复内容基于谷歌/Wikipedia
开启飞行模式，启用模块：情况参考最开始描述
开启飞行模式，启用模块，**关闭Siri的位置服务权限**：Siri建议、Visual Lookup均生效；Ask Siri请求不会访问guzzoni.apple.com，但此时Siri回复仍基于谷歌/Wikipedia

以上测试均在所有Apple服务走代理的情况下进行，网络工具为qx，定位服务模块设置地区为US。

由此得出的结论似乎是只有当Siri配置下发CN配置之后，Ask Siri相关请求才会访问guzzoni.apple.com，因为开启飞行模式后，如果再进行Ask Siri请求，qx的网络活动内看不到与guzzoni.apple.com有关的任何请求。

所以想问一下模块后续是否会对这一点进行优化

**Comment by VirgilClyne** [comment]
请关注后续开发
https://github.com/VirgilClyne/iRingo/raw/beta/sgmodule/Siri.V2.macOS.beta.sgmodule
https://github.com/VirgilClyne/iRingo/raw/beta/sgmodule/Siri.V2.beta.sgmodule

**Comment by NLasagna** [comment]
> 请关注后续开发 https://github.com/VirgilClyne/iRingo/raw/beta/sgmodule/Siri.V2.macOS.beta.sgmodule https://github.com/VirgilClyne/iRingo/raw/beta/sgmodule/Siri.V2.beta.sgmodule

目前访问不了这个beta了，是要上正式版了么👀btw tg群组被误封请问可以如何解决呢
