### ISSUE TITLE
建议 siri suggestions 也能提供多种语言版本

### ISSUE THREAD

**Issue by edgexyz** [VirgilClyne/iRingo#27]
目前 siri suggestions 是强制修改位置为 TW，语言为 zh-TW，但是会出现简介英文，点开详情变成繁体这样不连续的使用体验

应该可以提供一个改为 zh-TW，一个改为 en-US 两个版本

**Comment by Meonthb** [comment]
同求

**Comment by edgexyz** [comment]
已经提交了 pr
