### ISSUE TITLE
QX天气未生效

### ISSUE THREAD

**Issue by RayvChan** [VirgilClyne/iRingo#30]
查看连接，weather-analytics-events.apple.com,weather-map.apple.com,weather-data.apple.com都走的direct。

**Comment by XueTeng2** [comment]
iOS15.1 Quantumult X测试，天气仍为国区。

**Comment by VirgilClyne** [comment]
> iOS15.1 Quantumult X测试，天气仍为国区。

需要`最近请求`里，来自weather-data.apple.com的链接日志

**Comment by RayvChan** [comment]
![730100904](https://user-images.githubusercontent.com/38351030/139656891-70ccfcd3-2280-4ffa-a041-21b3209b4e77.jpg)
![1606610735](https://user-images.githubusercontent.com/38351030/139656904-a8c83f54-e68b-4320-a032-90a2333fe7ff.jpg)
![1823527864](https://user-images.githubusercontent.com/38351030/139656907-9166774a-4502-4963-ad99-9a276a7b022c.jpg)
![1980885723](https://user-images.githubusercontent.com/38351030/139656908-285e8e24-4d97-4209-b5df-c2017b2bcfe3.jpg)
![1850795023](https://user-images.githubusercontent.com/38351030/139656910-6fd6b5fd-00fa-4117-9e70-49ca00a9c3f4.jpg)

**Comment by RayvChan** [comment]
有GB和US可能是因为天气里添加了英国和美国的城市

**Comment by VirgilClyne** [comment]
> 有GB和US可能是因为天气里添加了英国和美国的城市

有日志吗🥲 我脚本里放置了日志输出🥲
像这样：
![image](https://user-images.githubusercontent.com/2111377/139657459-8a3e7788-e50d-42f7-9cac-2c4ec36ae8aa.png)

**Comment by RayvChan** [comment]
用的QX，请问这个日志需要在哪里查看呢

**Comment by VirgilClyne** [comment]
> 用的QX，请问这个日志需要在哪里查看呢

不知道啊🤷‍♂️要不你点粉色的请求链接试试🤔

**Comment by RayvChan** [comment]
原始请求地址：  
https://weather-data.apple.com/v2/weather/zh-Hans-CN/30.51/104.07?dataSets=currentWeather,forecastDaily,forecastHourly,severeWeather,airQuality,forecastNextHour&country=CN  
重写：  
^https?:\/\/(weather-data|weather-data-origin)\.apple\.com\/(v1|v2)\/weather.*(include=[a-z,_]{1,}|dataSets=[A-Za-z,]{1,}).*(country=[A-Z]{2})?.* url script-request-body https://raw.githubusercontent.com/VirgilClyne/iRingo/main/js/Apple_Weather.js  
  
后面的请求头，请求体，响应头，响应体都没有内容

**Comment by RayvChan** [comment]
另外，使用的是神机规则默认配置，weather-data.apple.com在规则china.list里走direct

**Comment by VirgilClyne** [comment]
> 另外，使用的是神机规则默认配置，weather-data.apple.com在规则china.list里走direct

知道问题了🤪我回去修

**Comment by XueTeng2** [comment]
> > 另外，使用的是神机规则默认配置，weather-data.apple.com在规则china.list里走direct
> 
> 知道问题了🤪我回去修

大佬辛苦💖

**Comment by VirgilClyne** [comment]
> 另外，使用的是神机规则默认配置，weather-data.apple.com在规则china.list里走direct

新版还有问题吗？

**Comment by zerotl** [comment]
我的地区设为美国 不生效

**Comment by VirgilClyne** [comment]
> 我的地区设为美国 不生效

空气品质和地区设置无关，有日志记录吗？

**Comment by wangxin6** [comment]
![image](https://user-images.githubusercontent.com/24645789/139794157-d36da4b3-b697-4b67-9c53-15722edf0934.png)

**Comment by wangxin6** [comment]
![image](https://user-images.githubusercontent.com/24645789/139794603-1b74401e-97c1-4710-8547-738ecd2da5b9.png)

**Comment by RayvChan** [comment]
[20316.zip](https://github.com/VirgilClyne/iRingo/files/7458230/20316.zip)

**Comment by zerotl** [comment]
[
![微信图片_20211102141427](https://user-images.githubusercontent.com/88430573/139795437-c1e791fc-b340-4ace-a672-ea01678a4d32.jpg)
](url)

**Comment by loveteda** [comment]
我这边用surge不生效...日志好长...需要截图哪一段？

**Comment by char1eslu** [comment]
额，我地区是美国，Geo也是US，map用的CN，用大佬的模块一次成功了，天气，地图右下角，apple watch都能改写成功。。。

**Comment by wangxin6** [comment]
地区是 US，Geo 也是 US，map 用的 CN。刚更新脚本以后，地图和 watch 显示 AQI 51， 天气显示 AQI 38 并显示来自“和风天气”的数据

**Comment by zerotl** [comment]
> 额，我地区是美国，GeoUS，地图用的CN，用大佬的模块一次了，天气，地图右下角，apple watch 能改写成功。。。

你用Surge 还是quantumultX

**Comment by VirgilClyne** [comment]
> [
> 
> ![微信图片_20211102141427](https://user-images.githubusercontent.com/88430573/139795437-c1e791fc-b340-4ace-a672-ea01678a4d32.jpg)
> 
> ](url)

请勿以task方式运行js脚本
安装链接里给了qxrewrite格式模块了啊😵‍💫

**Comment by VirgilClyne** [comment]
> 地区是 US，Geo 也是 US，map 用的 CN。刚更新脚本以后，地图和 watch 显示 AQI 51， 天气显示 AQI 38 并显示来自“和风天气”的数据

改好了，试试看😵‍💫
手表地图的api是v1版 iOS15天气app是v2版

**Comment by loveteda** [comment]
![image](https://user-images.githubusercontent.com/47378094/140010712-017efc79-5974-48ee-9772-78d1b13d2cfb.png)![image](https://user-images.githubusercontent.com/47378094/140010715-09c8f475-8e50-430f-8b34-00113b124156.png)我这里一直不成功...地区选的美国...GEO美国 MAP中国..APPLE链接走的日本代理..

**Comment by zerotl** [comment]
> 版

圈X还是不行 已经命中重写了

**Comment by zerotl** [comment]
JS脚本都没有运行
![Uploading 923B09E1-18FA-4626-B216-C5A76510C52B.png…]()

**Comment by zerotl** [comment]
![45407567-7C0F-4221-9AF6-0AC01EFB940C](https://user-images.githubusercontent.com/88430573/140011110-f9f4fba0-0e29-4bfd-bc25-565b710535c9.png)

**Comment by VirgilClyne** [comment]
> > 版
> 
> 圈X还是不行 已经命中重写了

我sb了，修改response我写成修改request了 已修复

**Comment by zerotl** [comment]
> > > 版
> > 
> > 
> > 圈X还是不行 已经命中重写了
> 
> 我sb了，修改response我写成修改request了 已修复

大佬牛啊 这次可以了

**Comment by wangxin6** [comment]
> > 地区是 US，Geo 也是 US，map 用的 CN。刚更新脚本以后，地图和 watch 显示 AQI 51， 天气显示 AQI 38 并显示来自“和风天气”的数据
> 
> 改好了，试试看😵‍💫 手表地图的api是v1版 iOS15天气app是v2版

iOS14.8 地图和天气已成功获取 US AQI。 watch 7.6.2 反而看不到 AQI，只有剩下紫外线指数和风速。

**Comment by XueTeng2** [comment]
iOS15.1 we测试，定位所在地空气质量为US，但是通过搜索添加的其他位置空气质量仍为CN

**Comment by zerotl** [comment]
> iOS15.1 Quantumult X测试，定位所在地空气质量为US，但是通过搜索添加的其他位置空气质量仍为CN

我的和你的正好相反 自动定位的为CN，搜索添加的为US。地图那里的正常

**Comment by VirgilClyne** [comment]
> > > 地区是 US，Geo 也是 US，map 用的 CN。刚更新脚本以后，地图和 watch 显示 AQI 51， 天气显示 AQI 38 并显示来自“和风天气”的数据
> > 
> > 
> > 改好了，试试看😵‍💫 手表地图的api是v1版 iOS15天气app是v2版
> 
> iOS14.8 地图和天气已成功获取 US AQI。 watch 7.6.2 反而看不到 AQI，只有剩下紫外线指数和风速。今天早上的版本 watch 可以看到AQI

⌚️的api有两个来源，你能查来源吗？

**Comment by zerotl** [comment]
> > iOS15.1 Quantumult X测试，定位所在地空气质量为US，但是通过搜索添加的其他位置空气质量仍为CN
> 
> 我的和你的正好相反 自动定位的为CN，搜索添加的为US。地图那里的正常

现在都正常使用了

**Comment by wangxin6** [comment]
> > > > 地区是 US，Geo 也是 US，map 用的 CN。刚更新脚本以后，地图和 watch 显示 AQI 51， 天气显示 AQI 38 并显示来自“和风天气”的数据
> > > 
> > > 
> > > 改好了，试试看😵‍💫 手表地图的api是v1版 iOS15天气app是v2版
> > 
> > 
> > iOS14.8 地图和天气已成功获取 US AQI。 watch 7.6.2 反而看不到 AQI，只有剩下紫外线指数和风速。今天早上的版本 watch 可以看到AQI
> 
> ⌚️的api有两个来源，你能查来源吗？

![image](https://user-images.githubusercontent.com/24645789/140017201-bc39e31d-b0c0-4175-a903-724ef8892705.png)

**Comment by wangxin6** [comment]
最新更新：

Watch 定位城市已恢复 AQI，但数据不是US。手动添加的城市没有 AQI 数据

**Comment by VirgilClyne** [comment]
> [c6a0b5b](https://github.com/VirgilClyne/iRingo/commit/c6a0b5b8c9e20026daffc59242867f95c8512b80) 之后，
> 地图和天气可以更新AQI；
> 小组件无 AQI；
> watch 无 AQI

应该是最终版本了，为啥还有问题🤔
小组件和watch连接的api以及日志记录有吗

**Comment by zerotl** [comment]
> > [c6a0b5b](https://github.com/VirgilClyne/iRingo/commit/c6a0b5b8c9e20026daffc59242867f95c8512b80) 之后，
> > 地图和天气可以更新AQI；
> > 小组件无 AQI；
> > watch 无 AQI
> 
> 应该是最终版本了，为啥还有问题🤔 小组件和watch连接的api以及日志记录有吗

小组件是iphone上的小组件吗？iphone上的小组件确实没有显示AQI

**Comment by wangxin6** [comment]
[26f8f7f](https://github.com/VirgilClyne/iRingo/commit/26f8f7f82a4b7bccb823a2d6ac8d7de36108eb54)

watch 没有AQI 显示。手机上显示的记录如下：
![IMG_2336](https://user-images.githubusercontent.com/24645789/140250897-b9e54c90-cc11-44fa-918f-43d3d4d38590.jpg)

小组件也没有看到 AQI。记录如下：
![IMG_72E5174D693F-1](https://user-images.githubusercontent.com/24645789/140251025-b29bb52e-423f-47c4-8f47-7b630979860c.jpeg)
![IMG_9264FE3CF06C-1](https://user-images.githubusercontent.com/24645789/140251042-1968a4cf-2bcf-461e-98f9-3d603583d855.jpeg)

**Comment by wangxin6** [comment]
ff25cdd 情况依旧

**Comment by VirgilClyne** [comment]
> [ff25cdd](https://github.com/VirgilClyne/iRingo/commit/ff25cdd99a8552d3d465a15fd61142dae33f1352) 情况依旧

第一张图`weather-data.apple.com`都没有链接成功啊，连地址都没获取到，你这dns解析有问题吧🤔

模块的作用只是把来自`weather-data.apple.com`的`空气质量`数据修改成`waqi.info`的，后面几张图看，从`waqi.info`获取数据都正常获取到了

**Comment by zerotl** [comment]
手机上的天气小组件没有AQI显示

**Comment by VirgilClyne** [comment]
> 手机上的天气小组件没有AQI显示

啊这，我只能解决提供了哪些天气数据，显示哪些信息我无法决定😵‍💫

**Comment by wangxin6** [comment]
99b7307

手机 - 地图、天气 AQI 显示 US 数据
手表 - 天气 AQI 显示 CN 数据

**Comment by VirgilClyne** [comment]
> 99b7307
> 
> 
> 
> 手机 - 地图、天气 AQI 显示 US 数据
> 
> 手表 - 不稳定，时有时无

手表不稳定的连接情况和日志有吗🤔

**Comment by wangxin6** [comment]
> > [99b7307](https://github.com/VirgilClyne/iRingo/commit/99b73075cf85e09892b253d75e5df3d1e1e112b7)
> > 手机 - 地图、天气 AQI 显示 US 数据
> > 手表 - 不稳定，时有时无
> 
> 手表不稳定的连接情况和日志有吗🤔


![](https://user-images.githubusercontent.com/24645789/140250897-b9e54c90-cc11-44fa-918f-43d3d4d38590.jpg)

**Comment by VirgilClyne** [comment]
> > > [99b7307](https://github.com/VirgilClyne/iRingo/commit/99b73075cf85e09892b253d75e5df3d1e1e112b7)
> > > 手机 - 地图、天气 AQI 显示 US 数据
> > > 手表 - 不稳定，时有时无
> > 
> > 
> > 手表不稳定的连接情况和日志有吗🤔
> 
> ![](https://user-images.githubusercontent.com/24645789/140250897-b9e54c90-cc11-44fa-918f-43d3d4d38590.jpg)

应该不是我的问题 你这连`weather-data.apple.com`都没正确解析和链接

**Comment by wangxin6** [comment]
也不知道为什这个 weather-data.apple.com 没有链接和解析。导致手表上看不到 AQI。手机端都是正常的

**Comment by VirgilClyne** [comment]
> 也不知道为什这个 weather-data.apple.com 没有链接和解析。导致手表上看不到 AQI。手机端都是正常的

你可以让weather-data.apple.com走代理，或者指定weather-data.apple.com所用的dns，或者全局模式试试

**Comment by wangxin6** [comment]
> > 也不知道为什这个 weather-data.apple.com 没有链接和解析。导致手表上看不到 AQI。手机端都是正常的
> 
> 你可以让weather-data.apple.com走代理，或者指定weather-data.apple.com所用的dns，或者全局模式试试

以上三种方法都试过了，还是不行。

刚才重启手机，手表可以看到 AQI 数据，和地图、天气的 AQI 数据一样是 CN 的数据。待 QX 的重写规则生效，地图和天气的 AQI 数据更新为 US 数据。但是手表 AQI 数据保持为 CN 数据。估计等手机缓存的 AQI 数据失效，就没有 AQI了。

问题出现在重写规则生效后，对 weather-data.apple.com 的访问。

地图和天气随时正确的访问到 weather-data.apple.com，但是手表发起的链接就会出现上述的情况

地图和天气的访问记录
![image](https://user-images.githubusercontent.com/24645789/140470494-caff6ee5-16c6-4481-9545-64a8304fcd62.png)

手表的访问记录

![](https://user-images.githubusercontent.com/24645789/140250897-b9e54c90-cc11-44fa-918f-43d3d4d38590.jpg)

**Comment by wangxin6** [comment]
重写的 JS 脚本阻断了手表发起的对 weather-data.apple.com 的访问？

**Comment by VirgilClyne** [comment]
> 重写的 JS 脚本阻断了手表发起的对 weather-data.apple.com 的访问？

不提供日志很难判断，我脚本里会根据情况输出调试信息的

**Comment by wangxin6** [comment]
> > 重写的 JS 脚本阻断了手表发起的对 weather-data.apple.com 的访问？
> 
> 不提供日志很难判断，我脚本里会根据情况输出调试信息的

手表上查看的时候，JS 没有运行，没有日志记录。只能看到上面的一个域名访问

**Comment by wangxin6** [comment]
在重写中关闭 Apple_Weather.qxerite 后，在QX上可以看到手表的 weather-data.apple.com 的访问被正确处理，数据当然是 CN 的。

![image](https://user-images.githubusercontent.com/24645789/140475783-87a9edae-7b88-4fdd-9048-790b9cd5772a.png)

**Comment by VirgilClyne** [comment]
> 在重写中关闭 Apple_Weather.qxerite 后，在QX上可以看到手表的 weather-data.apple.com 的访问被正确处理，数据当然是 CN 的。
> 
> ![image](https://user-images.githubusercontent.com/24645789/140475783-87a9edae-7b88-4fdd-9048-790b9cd5772a.png)

198.18.0.86应该是VPN创建的tun虚拟网卡的网段，你对比4楼正常解析出来的`weather-data.apple.com`的地址

**Comment by zerotl** [comment]
不显示AQI了
![17DAA613-BAF8-41F2-9C1A-AD8D24F2C774](https://user-images.githubusercontent.com/88430573/140605260-b19ff257-ba84-427c-bd2d-e62710967873.png)

**Comment by wangxin6** [comment]
> > 在重写中关闭 Apple_Weather.qxerite 后，在QX上可以看到手表的 weather-data.apple.com 的访问被正确处理，数据当然是 CN 的。
> > ![image](https://user-images.githubusercontent.com/24645789/140475783-87a9edae-7b88-4fdd-9048-790b9cd5772a.png)
> 
> 198.18.0.86应该是VPN创建的tun虚拟网卡的网段，你对比4楼正常解析出来的`weather-data.apple.com`的地址

这是关闭重写以后的网络连接。可以获取 AQI，只是数据是CN。
打开重写，网络环境不变，该地址就无法访问，也就无法获取AQI，同时日志里面也没有js的运行记录

**Comment by wangxin6** [comment]
在重写打开的情况
手机上的访问记录如下：
![IMG_73EFBD7630DF-1](https://user-images.githubusercontent.com/24645789/140635889-29feb945-fafb-4a91-bb9d-31df04753064.jpeg)

而 watch的访问记录完全不一样
![IMG_30BD8D03A02E-1](https://user-images.githubusercontent.com/24645789/140635904-f8b5b297-174f-4560-a54b-e64065d73d90.jpeg)

**Comment by edgexyz** [comment]
> 在重写打开的情况 手机上的访问记录如下： ![IMG_73EFBD7630DF-1](https://user-images.githubusercontent.com/24645789/140635889-29feb945-fafb-4a91-bb9d-31df04753064.jpeg)
> 
> 而 watch的访问记录完全不一样 ![IMG_30BD8D03A02E-1](https://user-images.githubusercontent.com/24645789/140635904-f8b5b297-174f-4560-a54b-e64065d73d90.jpeg)

应该是需要给 watch 和 手机同时装上根证书？现在的 watch 应该做不到

**Comment by VirgilClyne** [comment]
> > 在重写打开的情况 手机上的访问记录如下： ![IMG_73EFBD7630DF-1](https://user-images.githubusercontent.com/24645789/140635889-29feb945-fafb-4a91-bb9d-31df04753064.jpeg)
> > 而 watch的访问记录完全不一样 ![IMG_30BD8D03A02E-1](https://user-images.githubusercontent.com/24645789/140635904-f8b5b297-174f-4560-a54b-e64065d73d90.jpeg)
> 
> 应该是需要给 watch 和 手机同时装上根证书？现在的 watch 应该做不到

群里确实有修改⌚️AQI成功的，不确定是⌚️装证书，还是说⌚️的天气实际是从iOS设备的网络连接获取再调用的，我没有⌚️😭

**Comment by wangxin6** [comment]
> > 在重写打开的情况 手机上的访问记录如下： ![IMG_73EFBD7630DF-1](https://user-images.githubusercontent.com/24645789/140635889-29feb945-fafb-4a91-bb9d-31df04753064.jpeg)
> > 而 watch的访问记录完全不一样 ![IMG_30BD8D03A02E-1](https://user-images.githubusercontent.com/24645789/140635904-f8b5b297-174f-4560-a54b-e64065d73d90.jpeg)
> 
> 应该是需要给 watch 和 手机同时装上根证书？现在的 watch 应该做不到

感谢提醒。

将 QX 的证书下载导入到 watch 之后，AQI 已经可以成功获取并且为 US 数据。

并同时感谢 VirgilClyne 的工具。

**Comment by VirgilClyne** [comment]
> > > 在重写打开的情况 手机上的访问记录如下： ![IMG_73EFBD7630DF-1](https://user-images.githubusercontent.com/24645789/140635889-29feb945-fafb-4a91-bb9d-31df04753064.jpeg)
> 
> > > 而 watch的访问记录完全不一样 ![IMG_30BD8D03A02E-1](https://user-images.githubusercontent.com/24645789/140635904-f8b5b297-174f-4560-a54b-e64065d73d90.jpeg)
> 
> > 
> 
> > 应该是需要给 watch 和 手机同时装上根证书？现在的 watch 应该做不到
> 
> 
> 
> 感谢提醒。
> 
> 
> 
> 将 QX 的证书下载导入到 watch 之后，AQI 已经可以成功获取并且为 US 数据。
> 
> 
> 
> 并同时感谢 VirgilClyne 的工具。 
> 
> 

破案了 可喜可贺🤪

**Comment by WordlessEcho** [comment]
@RayvChan @wangxin6 @zerotl @VirgilClyne 日志中有您的个人信息，请注意删除日志并删除编辑记录

**Comment by WordlessEcho** [comment]
You can check commit history about this bug here: https://github.com/VirgilClyne/iRingo/commits/main?after=629b924f5676cfeb4d105a68f87d8a6016f01fcd+664&branch=main

**Comment by tontwoo** [comment]
> 查看连接，weather-analytics-events.apple.com,weather-map.apple.com,weather-data.apple.com都走的direct。
我的情况和你一样，上面这些都走的direct，添加了weather-data.apple.com分流规则，host-suffix，走direct，ios自带的天气app还是显示不了，请问你是怎么解决的？能否写的详细一点？谢谢
