### ISSUE TITLE
系统英文，surge，Geo-US，Map-CN，天气依然是CN标准，未切换

### ISSUE THREAD

**Issue by char1eslu** [VirgilClyne/iRingo#33]
之前版本还是可以的，发现随着最近的脚本更新，失效了。。
![IMG_5958](https://user-images.githubusercontent.com/20885743/140601310-2492179c-13d6-4afd-9d12-33e6be7968d8.PNG)
。

**Comment by VirgilClyne** [comment]
> 之前版本还是可以的，发现随着最近的脚本更新，失效了。。 ![IMG_5958](https://user-images.githubusercontent.com/20885743/140601310-2492179c-13d6-4afd-9d12-33e6be7968d8.PNG) 。

之前判断写反了 更新一下`外部资源`应该就好了

**Comment by char1eslu** [comment]
> > 之前版本还是可以的，发现随着最近的脚本更新，失效了。。 ![IMG_5958](https://user-images.githubusercontent.com/20885743/140601310-2492179c-13d6-4afd-9d12-33e6be7968d8.PNG) 。
> 
> 之前判断写反了 更新一下`外部资源`应该就好了

还是一样唉，天气里面的是CN的

**Comment by VirgilClyne** [comment]
> > > 之前版本还是可以的，发现随着最近的脚本更新，失效了。。 ![IMG_5958](https://user-images.githubusercontent.com/20885743/140601310-2492179c-13d6-4afd-9d12-33e6be7968d8.PNG) 。
> > 
> > 
> > 之前判断写反了 更新一下`外部资源`应该就好了
> 
> 还是一样唉，天气里面的是CN的

更新一下`外部资源` 就是js文件引用 你这个不是最新版 最新版的天气资源判断功能改成了`getAQIstatus`，你这个还是`AQIstatus`

**Comment by char1eslu** [comment]
> > > > 之前版本还是可以的，发现随着最近的脚本更新，失效了。。 ![IMG_5958](https://user-images.githubusercontent.com/20885743/140601310-2492179c-13d6-4afd-9d12-33e6be7968d8.PNG) 。
> 
> > > 
> 
> > > 
> 
> > > 之前判断写反了 更新一下`外部资源`应该就好了
> 
> > 
> 
> > 还是一样唉，天气里面的是CN的
> 
> 
> 
> 更新一下`外部资源` 就是js文件引用 你这个不是最新版 最新版的天气资源判断功能改成了`getAQIstatus`，你这个还是`AQIstatus`

![image](https://user-images.githubusercontent.com/20885743/140603855-a7108c14-d83e-475c-9d13-94630f7e8284.png)我重装看看，已经更新了其实

**Comment by char1eslu** [comment]
重装已解决，谢谢大佬

**Comment by WordlessEcho** [comment]
@char1eslu @VirgilClyne 日志中有您的个人信息（geo: []），请注意删除日志并删除编辑记录

**Comment by WordlessEcho** [comment]
> > 
> 
> 啊啊啊，大佬引用我的删不了。。。

我会叫他删，你先处理掉你的
