### ISSUE TITLE
重绘waqi.info的logo

### ISSUE THREAD

**Issue by edgexyz** [VirgilClyne/iRingo#35]
一是建议换一个 AQI provider logo 源。
现在请求的是 https://waqi.info/images/logo.png ，但它是彩色的🌚
![0AF24444-C168-4A65-BA40-6BA47190ADE5](https://user-images.githubusercontent.com/32131214/140612999-afa9af36-1df7-4ef0-bede-2e1e5f815ce7.jpeg)
![16078D9A-7E02-411C-932D-65BC57540B6D](https://user-images.githubusercontent.com/32131214/140613002-154eca5c-1d7a-4a1e-8dc1-646ed0bc7461.jpeg)
直接导致 weather 无法解析图片直接显示一个方块，或许可以在项目里自己重新绘制一个 logo 来引用？ ~~可惜我不会~~
可以参考 
![TWC](https://weather-data.apple.com/assets/v2/TWC.png)

其次是打开的空气质量地图还是以 AQI CN 为标准显示的（非 breezometer 提供），不知道能不能再做出这个的支持…？
看到 weather-map.apple.com 请求的时候带上了 uri: country=CN, header GeoCountryCode: CN
不知道修改这两个会不会有效果？

**Comment by VirgilClyne** [comment]
logo可以改 但是似乎要改成透明涂层的版本
breezometer等其他地区来源无中国空气质量地图数据 但是waqi.info有空气质量地图 我上个概念模块 可以试试

**Comment by wangxin6** [comment]
watch 上可以正确显示该彩色图标

**Comment by VirgilClyne** [comment]
> watch 上可以正确显示该彩色图标

猜测 采用V1版api的应该都能正确显示彩色图标

**Comment by zerotl** [comment]
> > watch 上可以正确显示该彩色图标
> 
> 猜测 采用V1版api的应该都能正确显示彩色图标

显示不了了
![微信图片_20211108111828](https://user-images.githubusercontent.com/88430573/140679111-1e907430-7b3b-4990-bebb-61638479ad4e.jpg)
![微信图片_20211108111835](https://user-images.githubusercontent.com/88430573/140679120-f5b31d08-ebb3-4eb9-84fe-3e65f1ec9f0c.jpg)

**Comment by VirgilClyne** [comment]
> > > watch 上可以正确显示该彩色图标
> 
> > 
> 
> > 猜测 采用V1版api的应该都能正确显示彩色图标
> 
> 
> 
> 显示不了了
> 
> ![微信图片_20211108111828](https://user-images.githubusercontent.com/88430573/140679111-1e907430-7b3b-4990-bebb-61638479ad4e.jpg)
> 
> ![微信图片_20211108111835](https://user-images.githubusercontent.com/88430573/140679120-f5b31d08-ebb3-4eb9-84fe-3e65f1ec9f0c.jpg)
> 
> 
应该是json格式化失败🤔
完整log发一下 我看看观测站id是哪个 有啥特别的地方

**Comment by zerotl** [comment]
![微信图片_20211108115235](https://user-images.githubusercontent.com/88430573/140681775-0134ceab-eed9-4c44-a436-10a43069621e.jpg)

**Comment by wangxin6** [comment]
请教一下这个小组件在哪里调用出来的？

<img width="616" alt="image" src="https://user-images.githubusercontent.com/24645789/140682402-fddfe1db-b099-413a-8949-ff5f96fc772f.png">

**Comment by VirgilClyne** [comment]
> 请教一下这个小组件在哪里调用出来的？
> 
> 
> 
> <img width="616" alt="image" src="https://user-images.githubusercontent.com/24645789/140682402-fddfe1db-b099-413a-8949-ff5f96fc772f.png">
> 
> 

长按/重按地图中右下角的天气小组件

**Comment by VirgilClyne** [comment]
> > > watch 上可以正确显示该彩色图标
> > 
> > 
> > 猜测 采用V1版api的应该都能正确显示彩色图标
> 
> 显示不了了 ![微信图片_20211108111828](https://user-images.githubusercontent.com/88430573/140679111-1e907430-7b3b-4990-bebb-61638479ad4e.jpg) ![微信图片_20211108111835](https://user-images.githubusercontent.com/88430573/140679120-f5b31d08-ebb3-4eb9-84fe-3e65f1ec9f0c.jpg)

这个你访问正常吗？
https://api.waqi.info/api/feed/@789/aqi.json

**Comment by zerotl** [comment]
![E2DA0E6B-D867-4517-BE38-4080067EB4F0](https://user-images.githubusercontent.com/88430573/140683881-74bf54e8-6d72-4396-ad12-156651d87b3a.png)打开很慢

**Comment by edgexyz** [comment]
<img width="1440" alt="Screen Shot 2021-11-08 at 12 24 42" src="https://user-images.githubusercontent.com/32131214/140684193-4979b243-9066-469e-b6da-ba1413fcc0dc.png">

**Comment by VirgilClyne** [comment]
> ![E2DA0E6B-D867-4517-BE38-4080067EB4F0](https://user-images.githubusercontent.com/88430573/140683881-74bf54e8-6d72-4396-ad12-156651d87b3a.png)打开很慢
> 
> 

你楼下截图的那个是正常的情况🤔

**Comment by VirgilClyne** [comment]
> ![E2DA0E6B-D867-4517-BE38-4080067EB4F0](https://user-images.githubusercontent.com/88430573/140683881-74bf54e8-6d72-4396-ad12-156651d87b3a.png)打开很慢
> 
> 

你换个IP地址或者4G网络试试呢🤔 我怎么觉得是你被限制获取了🤔

**Comment by zerotl** [comment]
是什么原因呢？前几天还用得很好好的

**Comment by zerotl** [comment]
👌了 还有这种操作

**Comment by edgexyz** [comment]
![4B1B2B14-F416-4619-9648-28196A725459](https://user-images.githubusercontent.com/32131214/140818635-82f2f87b-a7ea-4fd0-8000-27258bc79cd7.jpeg)
![50DB688B-C8EC-4833-BFC2-05D2AD72A9A8](https://user-images.githubusercontent.com/32131214/140818646-fc61e399-0e3a-4df5-b915-5d4cf205081f.jpeg)
不知道是什么原因，大陆区域的指标和描述不太匹配…

**Comment by VirgilClyne** [comment]
> ![4B1B2B14-F416-4619-9648-28196A725459](https://user-images.githubusercontent.com/32131214/140818635-82f2f87b-a7ea-4fd0-8000-27258bc79cd7.jpeg)
> ![50DB688B-C8EC-4833-BFC2-05D2AD72A9A8](https://user-images.githubusercontent.com/32131214/140818646-fc61e399-0e3a-4df5-b915-5d4cf205081f.jpeg)
> 不知道是什么原因，大陆区域的指标和描述不太匹配…

更新外部文件（js文件）增加了空气质量分级转换

**Comment by gdopera** [comment]
期待

**Comment by ranckinuta** [comment]
試試這個，我剛做好的waqi.info的圖標，若有問題我再進行修改
![logo](https://user-images.githubusercontent.com/30703731/165332744-dea74034-6dac-48fc-a1fc-4b14c706da00.png)

**Comment by ranckinuta** [comment]
> 

兩者皆是，它是灰階的透明圖

**Comment by VirgilClyne** [comment]
> > 
> 
> 兩者皆是，它是灰階的透明圖

那你可以直接pull request 替换
https://github.com/VirgilClyne/iRingo/blob/main/image/waqi.info.logo.png

**Comment by VirgilClyne** [comment]
Resolved #81 
thanks @ranckinuta
