### ISSUE TITLE
圈X新版定位服务无法解锁apple news

### ISSUE THREAD

**Issue by Pollo3470** [VirgilClyne/iRingo#37]
iphone,quantumult x,用旧版定位改为US可以正常解锁apple news，新版就会导致解锁失效，不知道是不是新版的有什么地方不兼容

**Comment by VirgilClyne** [comment]
> iphone,quantumult x,用旧版定位改为US可以正常解锁apple news，新版就会导致解锁失效，不知道是不是新版的有什么地方不兼容

新版定位服务下，浏览器访问 https://gspe1-ssl.ls.apple.com/pep/gcc ，页面显示的字母是US吗？

**Comment by Pollo3470** [comment]
是一个空白页面
![Uploading IMG_1228.PNG…]()

**Comment by bryanwongxin** [comment]
> > iphone,quantumult x,用旧版定位改为US可以正常解锁apple news，新版就会导致解锁失效，不知道是不是新版的有什么地方不兼容
> 
> 新版定位服务下，浏览器访问 https://gspe1-ssl.ls.apple.com/pep/gcc ，页面显示的字母是US吗？

显示cn 就是实效了对吧

**Comment by VirgilClyne** [comment]
> > > iphone,quantumult x,用旧版定位改为US可以正常解锁apple news，新版就会导致解锁失效，不知道是不是新版的有什么地方不兼容
> > 
> > 
> > 新版定位服务下，浏览器访问 https://gspe1-ssl.ls.apple.com/pep/gcc ，页面显示的字母是US吗？
> 
> 显示cn 就是失效了对吧

对

**Comment by char1eslu** [comment]
我的天气app直接不显示AQI了。。。

**Comment by VirgilClyne** [comment]
> 我的天气app直接不显示AQI了。。。

天气模块已经23小时没有更新过了

**Comment by MichaelPan1026** [comment]
我的访问页面也是空白页面，并且只有关掉飞行模式才会解锁成功，失效后开启飞行模式不会解锁成功。

**Comment by char1eslu** [comment]
> > 我的天气app直接不显示AQI了。。。
> 
> 天气模块已经23小时没有更新过了

啊啊啊，我也不清楚为啥突然消失了，，，。就是不出来AQI了，难受

**Comment by VirgilClyne** [comment]
> > > 我的天气app直接不显示AQI了。。。
> > 
> > 
> > 天气模块已经23小时没有更新过了
> 
> 啊啊啊，我也不清楚为啥突然消失了，，，。就是不出来AQI了，难受

你换个网络环境试试看，或者更新一下外部文件 js脚本

**Comment by char1eslu** [comment]
> > > > 我的天气app直接不显示AQI了。。。
> > > 
> > > 
> > > 天气模块已经23小时没有更新过了
> > 
> > 
> > 啊啊啊，我也不清楚为啥突然消失了，，，。就是不出来AQI了，难受
> 
> 你换个网络环境试试看，或者更新一下外部文件 js脚本

唉，不得行，换网络也不得行；我把模块删了，然后更新外部文件，然后重新安装，然后再更新外部文件，也不行

**Comment by VirgilClyne** [comment]
> > > > > 我的天气app直接不显示AQI了。。。
> > > > 
> > > > 
> > > > 天气模块已经23小时没有更新过了
> > > 
> > > 
> > > 啊啊啊，我也不清楚为啥突然消失了，，，。就是不出来AQI了，难受
> > 
> > 
> > 你换个网络环境试试看，或者更新一下外部文件 js脚本
> 
> 唉，不得行，换网络也不得行；我把模块删了，然后更新外部文件，然后重新安装，然后再更新外部文件，也不行

发日志

**Comment by char1eslu** [comment]
> > > > > > 我的天气app直接不显示AQI了。。。
> 
> > > > > 
> 
> > > > > 
> 
> > > > > 天气模块已经23小时没有更新过了
> 
> > > > 
> 
> > > > 
> 
> > > > 啊啊啊，我也不清楚为啥突然消失了，，，。就是不出来AQI了，难受
> 
> > > 
> 
> > > 
> 
> > > 你换个网络环境试试看，或者更新一下外部文件 js脚本
> 
> > 
> 
> > 唉，不得行，换网络也不得行；我把模块删了，然后更新外部文件，然后重新安装，然后再更新外部文件，也不行
> 
> 
> 
> 发日志

![image](https://user-images.githubusercontent.com/20885743/140933524-94259823-680f-453e-94ae-af501b271171.png)![image](https://user-images.githubusercontent.com/20885743/140933546-e0682b0c-44e8-4b48-a3c5-3c2a322651c8.png)![image](https://user-images.githubusercontent.com/20885743/140933556-e8e9176c-799b-4ac4-88aa-8ffb3f1e82f5.png)

**Comment by Pollo3470** [comment]
> > 是一个空白页面 ![IMG_1228](https://user-images.githubusercontent.com/90445326/140927180-0c5afd26-5357-4c5e-ac78-b27fd62d6c55.PNG)
> 
> 已更新脚本 试试看
> 
> > 我的访问页面也是空白页面，并且只有关掉飞行模式才会解锁成功，失效后开启飞行模式不会解锁成功。
> 
> 已更新脚本 试试看

还是空白页面

**Comment by VirgilClyne** [comment]
> > > > > > > 我的天气app直接不显示AQI了。。。
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > 天气模块已经23小时没有更新过了
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > 啊啊啊，我也不清楚为啥突然消失了，，，。就是不出来AQI了，难受
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 你换个网络环境试试看，或者更新一下外部文件 js脚本
> > 
> > 
> > > 
> > 
> > 
> > > 唉，不得行，换网络也不得行；我把模块删了，然后更新外部文件，然后重新安装，然后再更新外部文件，也不行
> > 
> > 
> > 发日志
> 
> ![image](https://user-images.githubusercontent.com/20885743/140933524-94259823-680f-453e-94ae-af501b271171.png)![image](https://user-images.githubusercontent.com/20885743/140933546-e0682b0c-44e8-4b48-a3c5-3c2a322651c8.png)![image](https://user-images.githubusercontent.com/20885743/140933556-e8e9176c-799b-4ac4-88aa-8ffb3f1e82f5.png)

https://api.waqi.info/api/feed/@928/aqi.json
https://api.waqi.info/api/feed/@7125/aqi.json
你浏览器访问看是不是空数据

**Comment by VirgilClyne** [comment]
> > > 是一个空白页面 ![IMG_1228](https://user-images.githubusercontent.com/90445326/140927180-0c5afd26-5357-4c5e-ac78-b27fd62d6c55.PNG)
> > 
> > 
> > 已更新脚本 试试看
> > > 我的访问页面也是空白页面，并且只有关掉飞行模式才会解锁成功，失效后开启飞行模式不会解锁成功。
> > 
> > 
> > 已更新脚本 试试看
> 
> 还是空白页面

求日志

**Comment by char1eslu** [comment]
> > > > > > > > 我的天气app直接不显示AQI了。。。
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > 天气模块已经23小时没有更新过了
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > 啊啊啊，我也不清楚为啥突然消失了，，，。就是不出来AQI了，难受
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 你换个网络环境试试看，或者更新一下外部文件 js脚本
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 唉，不得行，换网络也不得行；我把模块删了，然后更新外部文件，然后重新安装，然后再更新外部文件，也不行
> 
> > > 
> 
> > > 
> 
> > > 发日志
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/20885743/140933524-94259823-680f-453e-94ae-af501b271171.png)![image](https://user-images.githubusercontent.com/20885743/140933546-e0682b0c-44e8-4b48-a3c5-3c2a322651c8.png)![image](https://user-images.githubusercontent.com/20885743/140933556-e8e9176c-799b-4ac4-88aa-8ffb3f1e82f5.png)
> 
> 
> 
> https://api.waqi.info/api/feed/@928/aqi.json
> 
> https://api.waqi.info/api/feed/@7125/aqi.json
> 
> 你浏览器访问看是不是空数据

![image](https://user-images.githubusercontent.com/20885743/140934974-4edc0cb4-7bf0-4b67-931f-14b6911e7f39.png)![image](https://user-images.githubusercontent.com/20885743/140934999-483a1607-9df7-4c20-8ba0-0b1c46118701.png)

**Comment by char1eslu** [comment]
> > > > > > > > > 我的天气app直接不显示AQI了。。。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > 天气模块已经23小时没有更新过了
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > 啊啊啊，我也不清楚为啥突然消失了，，，。就是不出来AQI了，难受
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 你换个网络环境试试看，或者更新一下外部文件 js脚本
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 唉，不得行，换网络也不得行；我把模块删了，然后更新外部文件，然后重新安装，然后再更新外部文件，也不行
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 发日志
> > 
> > 
> > > 
> > 
> > 
> > > ![image](https://user-images.githubusercontent.com/20885743/140933524-94259823-680f-453e-94ae-af501b271171.png)![image](https://user-images.githubusercontent.com/20885743/140933546-e0682b0c-44e8-4b48-a3c5-3c2a322651c8.png)![image](https://user-images.githubusercontent.com/20885743/140933556-e8e9176c-799b-4ac4-88aa-8ffb3f1e82f5.png)
> > 
> > 
> > https://api.waqi.info/api/feed/@928/aqi.json
> > https://api.waqi.info/api/feed/@7125/aqi.json
> > 你浏览器访问看是不是空数据
> 
> ![image](https://user-images.githubusercontent.com/20885743/140934974-4edc0cb4-7bf0-4b67-931f-14b6911e7f39.png)![image](https://user-images.githubusercontent.com/20885743/140934999-483a1607-9df7-4c20-8ba0-0b1c46118701.png)

加载时间很长

**Comment by VirgilClyne** [comment]
> > > > > > > > > > 我的天气app直接不显示AQI了。。。
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > > > 天气模块已经23小时没有更新过了
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > > 啊啊啊，我也不清楚为啥突然消失了，，，。就是不出来AQI了，难受
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > 你换个网络环境试试看，或者更新一下外部文件 js脚本
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > 唉，不得行，换网络也不得行；我把模块删了，然后更新外部文件，然后重新安装，然后再更新外部文件，也不行
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 发日志
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > ![image](https://user-images.githubusercontent.com/20885743/140933524-94259823-680f-453e-94ae-af501b271171.png)![image](https://user-images.githubusercontent.com/20885743/140933546-e0682b0c-44e8-4b48-a3c5-3c2a322651c8.png)![image](https://user-images.githubusercontent.com/20885743/140933556-e8e9176c-799b-4ac4-88aa-8ffb3f1e82f5.png)
> 
> > > 
> 
> > > 
> 
> > > https://api.waqi.info/api/feed/@928/aqi.json
> 
> > > https://api.waqi.info/api/feed/@7125/aqi.json
> 
> > > 你浏览器访问看是不是空数据
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/20885743/140934974-4edc0cb4-7bf0-4b67-931f-14b6911e7f39.png)![image](https://user-images.githubusercontent.com/20885743/140934999-483a1607-9df7-4c20-8ba0-0b1c46118701.png)
> 
> 
> 
> 加载时间很长

要么网络超时 要么你被限制获取数据了 换个IP地址或者网络环境就好了 你是刷的有多频繁啊🤔

**Comment by char1eslu** [comment]
> > > > > > > > > > > 我的天气app直接不显示AQI了。。。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > > > 天气模块已经23小时没有更新过了
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > > 啊啊啊，我也不清楚为啥突然消失了，，，。就是不出来AQI了，难受
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > 你换个网络环境试试看，或者更新一下外部文件 js脚本
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > 唉，不得行，换网络也不得行；我把模块删了，然后更新外部文件，然后重新安装，然后再更新外部文件，也不行
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 发日志
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > ![image](https://user-images.githubusercontent.com/20885743/140933524-94259823-680f-453e-94ae-af501b271171.png)![image](https://user-images.githubusercontent.com/20885743/140933546-e0682b0c-44e8-4b48-a3c5-3c2a322651c8.png)![image](https://user-images.githubusercontent.com/20885743/140933556-e8e9176c-799b-4ac4-88aa-8ffb3f1e82f5.png)
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > https://api.waqi.info/api/feed/@928/aqi.json
> > 
> > 
> > > > https://api.waqi.info/api/feed/@7125/aqi.json
> > 
> > 
> > > > 你浏览器访问看是不是空数据
> > 
> > 
> > > 
> > 
> > 
> > > ![image](https://user-images.githubusercontent.com/20885743/140934974-4edc0cb4-7bf0-4b67-931f-14b6911e7f39.png)![image](https://user-images.githubusercontent.com/20885743/140934999-483a1607-9df7-4c20-8ba0-0b1c46118701.png)
> > 
> > 
> > 加载时间很长
> 
> 要么网络超时 要么你被限制获取数据了 换个IP地址或者网络环境就好了 你是刷的有多频繁啊🤔

哈哈哈，没有频繁去看啊。那我明天再看看吧，限制的话会很久吗

**Comment by VirgilClyne** [comment]
> 是一个空白页面
> 
> ![IMG_1228](https://user-images.githubusercontent.com/90445326/140927180-0c5afd26-5357-4c5e-ac78-b27fd62d6c55.PNG)
> 
> 
> 
> 

使用是这个文件吗？
qxrewrite/Geo_Services.qxrewrite

**Comment by VirgilClyne** [comment]
> > > 是一个空白页面 ![IMG_1228](https://user-images.githubusercontent.com/90445326/140927180-0c5afd26-5357-4c5e-ac78-b27fd62d6c55.PNG)
> 
> > 
> 
> > 已更新脚本 试试看
> 
> > 
> 
> > > 我的访问页面也是空白页面，并且只有关掉飞行模式才会解锁成功，失效后开启飞行模式不会解锁成功。
> 
> > 
> 
> > 已更新脚本 试试看
> 
> 
> 
> 还是空白页面

内容是这个里面的内容吗？引用方法是script-echo-response
https://github.com/VirgilClyne/iRingo/blob/main/qxrewrite/Geo_Services.qxrewrite

**Comment by Pollo3470** [comment]
> > > > 是一个空白页面 ![IMG_1228](https://user-images.githubusercontent.com/90445326/140927180-0c5afd26-5357-4c5e-ac78-b27fd62d6c55.PNG)
> > 
> > 
> > > 
> > 
> > 
> > > 已更新脚本 试试看
> > 
> > 
> > > 
> > 
> > 
> > > > 我的访问页面也是空白页面，并且只有关掉飞行模式才会解锁成功，失效后开启飞行模式不会解锁成功。
> > 
> > 
> > > 
> > 
> > 
> > > 已更新脚本 试试看
> > 
> > 
> > 还是空白页面
> 
> 内容是这个里面的内容吗？引用方法是script-echo-response https://github.com/VirgilClyne/iRingo/blob/main/qxrewrite/Geo_Services.qxrewrite

我放在rewrite_remote里的

**Comment by VirgilClyne** [comment]
> > > > > 是一个空白页面 ![IMG_1228](https://user-images.githubusercontent.com/90445326/140927180-0c5afd26-5357-4c5e-ac78-b27fd62d6c55.PNG)
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 已更新脚本 试试看
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > > 我的访问页面也是空白页面，并且只有关掉飞行模式才会解锁成功，失效后开启飞行模式不会解锁成功。
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 已更新脚本 试试看
> 
> > > 
> 
> > > 
> 
> > > 还是空白页面
> 
> > 
> 
> > 内容是这个里面的内容吗？引用方法是script-echo-response https://github.com/VirgilClyne/iRingo/blob/main/qxrewrite/Geo_Services.qxrewrite
> 
> 
> 
> 我放在rewrite_remote里的

求日志啊求日志

**Comment by Pollo3470** [comment]
> > > > > > 是一个空白页面 ![IMG_1228](https://user-images.githubusercontent.com/90445326/140927180-0c5afd26-5357-4c5e-ac78-b27fd62d6c55.PNG)
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 已更新脚本 试试看
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 我的访问页面也是空白页面，并且只有关掉飞行模式才会解锁成功，失效后开启飞行模式不会解锁成功。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 已更新脚本 试试看
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 还是空白页面
> > 
> > 
> > > 
> > 
> > 
> > > 内容是这个里面的内容吗？引用方法是script-echo-response https://github.com/VirgilClyne/iRingo/blob/main/qxrewrite/Geo_Services.qxrewrite
> > 
> > 
> > 我放在rewrite_remote里的
> 
> 求日志啊求日志

> > > > > > 是一个空白页面 ![IMG_1228](https://user-images.githubusercontent.com/90445326/140927180-0c5afd26-5357-4c5e-ac78-b27fd62d6c55.PNG)
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 已更新脚本 试试看
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 我的访问页面也是空白页面，并且只有关掉飞行模式才会解锁成功，失效后开启飞行模式不会解锁成功。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 已更新脚本 试试看
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 还是空白页面
> > 
> > 
> > > 
> > 
> > 
> > > 内容是这个里面的内容吗？引用方法是script-echo-response https://github.com/VirgilClyne/iRingo/blob/main/qxrewrite/Geo_Services.qxrewrite
> > 
> > 
> > 我放在rewrite_remote里的
> 
> 求日志啊求日志

没有日志是怎么回事
![IMG_1229](https://user-images.githubusercontent.com/90445326/140946413-200effb4-6ae9-4103-985a-9090887217f5.PNG)

**Comment by ti4n1993** [comment]
还是解锁不了啊，访问https://gspe1-ssl.ls.apple.com/pep/gcc是空白页

**Comment by WordlessEcho** [comment]
> 还是解锁不了啊，访问https://gspe1-ssl.ls.apple.com/pep/gcc 是空白页

新开一个issue并提供日志

**Comment by WordlessEcho** [comment]
@VirgilClyne @char1eslu 日志中有您的个人信息（geo: []），请注意删除日志并删除编辑记录
