### ISSUE TITLE
「定位服务」和「Siri与搜索」的位置关系是什么呢？

### ISSUE THREAD

**Issue by LoneFireBlossom** [VirgilClyne/iRingo#38]
用了一段时间了，今天有时间再次详细地看说明文档并且更新一下模块，没有太看懂题目中两个模块的说明。
比如：
- 如果要启用🇯🇵Siri的话，必须要用🇯🇵定位服务吗？如果是的话那🇭🇰呢，没看到有Siri香港是咋回事呢？
- Siri模块中的「激活过程中采用不同地区的Geo_Services_*.sgmodule模块」和「更改设置-通用-语言与地区-地区」，好像隐含了定位模块和Siri模块的地区可以不一样的意思……？
- 比如说，如果一直启用定位🇺🇸和🇯🇵Siri的话，会有什么坏处么？

**Comment by VirgilClyne** [comment]
> 用了一段时间了，今天有时间再次详细地看说明文档并且更新一下模块，没有太看懂题目中两个模块的说明。
> 
> 比如：
> 
> - 如果要启用🇯🇵Siri的话，必须要用🇯🇵定位服务吗？如果是的话那🇭🇰呢，没看到有Siri香港是咋回事呢？
> 

只用Siri建议模块就可以了，没有必要定位模块
没有香港模块是因为香港和台湾都是中华区 香港内容比台湾少 食之无味

> - Siri模块中的「激活过程中采用不同地区的Geo_Services_*.sgmodule模块」和「更改设置-通用-语言与地区-地区」，好像隐含了定位模块和Siri模块的地区可以不一样的意思……？
> 

对于Siri建议：自身设置>SIM地区检测>网络地区检测
所以可以用不同地区的模块搭配使用达成混合效果，readme开头的举例已经说明了

> - 比如说，如果一直启用定位🇺🇸和🇯🇵Siri的话，会有什么坏处么？

没有坏处
readme的建议配置就是
定位美国+天气美国+地图中国+Siri台湾+新闻美国
