### ISSUE TITLE
还是weather

### ISSUE THREAD

**Issue by char1eslu** [VirgilClyne/iRingo#39]
![image](https://user-images.githubusercontent.com/20885743/141514242-d7353c6e-8b95-4093-b170-6eeb0ab6c649.png)

**Comment by char1eslu** [comment]
打开天气后能在surge看到weather的请求，然后过了很久，发现脚本才工作

**Comment by VirgilClyne** [comment]
这个进程是天气的`下一小时降水强度`(WeatherKit_weatherd_iOS_Version) 的雨雪通知，国区没有提供`下一小时降水强度`数据，可以在`天气`-`通知`里开关，这个进程改写报错不影响使用，我还是排除一下这个链接好了

**Comment by char1eslu** [comment]
唉，想用大佬的模块，但是用就是不出AQI的那一小块，不知道啥情况

**Comment by VirgilClyne** [comment]
> 唉，想用大佬的模块，但是用就是不出AQI的那一小块，不知道啥情况

发日志啊 别发WeatherKit_weatherd_iOS_Version进程的日志，脚本里我都写了日志输出了，有错误我都标记了

**Comment by char1eslu** [comment]
![image](https://user-images.githubusercontent.com/20885743/141610301-8d66cb52-e49d-41f5-bc68-2242d6503095.png)好像是修改成功了？但是就是没有aqi那一行内容了，而且加载天气特别慢，然后，地图右下角也没有温度和aqi

**Comment by char1eslu** [comment]
不行大佬我们tg联系吧？我还可以录视频什么的@charles_lu

**Comment by char1eslu** [comment]
在大佬的指导下，日志m=-1，数据为空，设置api.waqi.info和api.aqicn.org走代理（US节点）后可以正常运行，感谢大佬

**Comment by WordlessEcho** [comment]
截图中有您的经纬度坐标（geo: []），请注意保护个人隐私
