### ISSUE TITLE
之前使用正常…这两天天气一直不显示了…

### ISSUE THREAD

**Issue by loveteda** [VirgilClyne/iRingo#40]
有时候能显示出来..大部分时间都是这样...![image](https://user-images.githubusercontent.com/47378094/141664717-ae7610ad-fcbb-44ee-9646-1861fa236776.png)![image](https://user-images.githubusercontent.com/47378094/141664720-ee625b61-eaab-4d3d-9e98-8102606a9546.png)![image](https://user-images.githubusercontent.com/47378094/141664722-2f449e42-2a04-49ca-916d-39e0c8dee03d.png)

**Comment by char1eslu** [comment]
换个节点试试呢，好像是超时了，大佬说最近api.waqi.info和api.aqicn.org最近服务器都在东京，我之前用香港的节点也是刷不出，然后换了个美国的节点可以了，你可以试试其他的

**Comment by loveteda** [comment]
> 换个节点试试呢，好像是超时了，大佬说最近api.waqi.info和api.aqicn.org最近服务器都在东京，我之前用香港的节点也是刷不出，然后换了个美国的节点可以了，你可以试试其他的

我一直用的日本节点...刚换美国香港的试了试...都不行...

**Comment by VirgilClyne** [comment]
> > 换个节点试试呢，好像是超时了，大佬说最近api.waqi.info和api.aqicn.org最近服务器都在东京，我之前用香港的节点也是刷不出，然后换了个美国的节点可以了，你可以试试其他的
> 
> 我一直用的日本节点...刚换美国香港的试了试...都不行...

我傻逼了，我以为setTimeout的单位是秒就设置了个5，原来单位是毫秒，改成5000了🤪

**Comment by WordlessEcho** [comment]
请注意您日志截图的个人隐私，删除编辑记录
![image](https://user-images.githubusercontent.com/12007025/165078958-a2fd48fb-3c5d-4415-8672-fa9977c56606.png)
