### ISSUE TITLE
TV模块无法观看体育直播

### ISSUE THREAD

**Issue by Meonthb** [VirgilClyne/iRingo#41]
如图所示，体育直播要求位置权限，但不管给不给都显示无法在我所在的地区播放，不知道模块能否解决这个问题

**Comment by VirgilClyne** [comment]
体育节目这块我用的少，一种是订阅后直接在apple tv app内观看直播，一种是跳转第三方app观看直播，前者应该是要求美区账号

**Comment by bryanwongxin** [comment]
> 体育节目这块我用的少，一种是订阅后直接在apple tv app内观看直播，一种是跳转第三方app观看直播，前者应该是要求美区账号 

我以为可以破解订阅......

**Comment by VirgilClyne** [comment]
> > 体育节目这块我用的少，一种是订阅后直接在apple tv app内观看直播，一种是跳转第三方app观看直播，前者应该是要求美区账号 
> 
> 
> 
> 我以为可以破解订阅......
> 
> 
> 
> 

想多了 破了我就没了🤪

**Comment by bryanwongxin** [comment]
> > > 体育节目这块我用的少，一种是订阅后直接在apple tv app内观看直播，一种是跳转第三方app观看直播，前者应该是要求美区账号
> > 
> > 
> > 我以为可以破解订阅......
> 
> 想多了 破了我就没了🤪

我之前用apple one的,现在不订阅了..

所以问下,这个不是破解订阅的,那什么叫解锁全功能呢?

**Comment by wangxin6** [comment]
https://github.com/VirgilClyne/iRingo#功能列表-2

**Comment by VirgilClyne** [comment]
> > > > 体育节目这块我用的少，一种是订阅后直接在apple tv app内观看直播，一种是跳转第三方app观看直播，前者应该是要求美区账号
> 
> > > 
> 
> > > 
> 
> > > 我以为可以破解订阅......
> 
> > 
> 
> > 想多了 破了我就没了🤪
> 
> 
> 
> 我之前用apple one的,现在不订阅了..
> 
> 
> 
> 所以问下,这个不是破解订阅的,那什么叫解锁全功能呢?不是订阅了就可以解锁全功能了么....

你国区正常情况下能用Siri建议吗？🙄️
能用appleNews吗？🙄️
能在地区检测为外区的情况下保持国区地图吗🙄️
非美英区账号，apple tv有电视节目体育节目儿童板块么？🙄️
想要破解自己动手

**Comment by bryanwongxin** [comment]
> > > > > 体育节目这块我用的少，一种是订阅后直接在apple tv app内观看直播，一种是跳转第三方app观看直播，前者应该是要求美区账号
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 我以为可以破解订阅......
> > 
> > 
> > > 
> > 
> > 
> > > 想多了 破了我就没了🤪
> > 
> > 
> > 我之前用apple one的,现在不订阅了..
> > 所以问下,这个不是破解订阅的,那什么叫解锁全功能呢?不是订阅了就可以解锁全功能了么....
> 
> 你国区正常情况下能用Siri建议吗？🙄️ 能用appleNews吗？🙄️ 能在地区检测为外区的情况下保持国区地图吗🙄️ 非美英区账号，apple tv有电视节目体育节目儿童板块么？🙄️ 想要破解自己动手


其他我知道要破解,特别是siri只能搜百度搞了好年没成功,
我刚刚是说apple tv的全功能解锁....
原来这些不解锁还不能看啊?我只是看看apple的自制剧.我孤陋了...

**Comment by VirgilClyne** [comment]
> > > > > > 体育节目这块我用的少，一种是订阅后直接在apple tv app内观看直播，一种是跳转第三方app观看直播，前者应该是要求美区账号
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > 我以为可以破解订阅......
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 想多了 破了我就没了🤪
> > > 
> > > 
> > > 我之前用apple one的,现在不订阅了..
> > > 所以问下,这个不是破解订阅的,那什么叫解锁全功能呢?不是订阅了就可以解锁全功能了么....
> > 
> > 
> > 你国区正常情况下能用Siri建议吗？🙄️ 能用appleNews吗？🙄️ 能在地区检测为外区的情况下保持国区地图吗🙄️ 非美英区账号，apple tv有电视节目体育节目儿童板块么？🙄️ 想要破解自己动手
> 
> 其他我知道要破解,特别是siri只能搜百度搞了好年没成功, 我刚刚是说apple tv的全功能解锁.... 原来这些不解锁还不能看啊?我只是看看apple的自制剧.我孤陋了...

主要目的是把因为地区限定导致缺少的服务和功能加回来

**Comment by bryanwongxin** [comment]
> > > > > > > 体育节目这块我用的少，一种是订阅后直接在apple tv app内观看直播，一种是跳转第三方app观看直播，前者应该是要求美区账号
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > > 我以为可以破解订阅......
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > 想多了 破了我就没了🤪
> > > > 
> > > > 
> > > > 我之前用apple one的,现在不订阅了..
> > > > 所以问下,这个不是破解订阅的,那什么叫解锁全功能呢?不是订阅了就可以解锁全功能了么....
> > > 
> > > 
> > > 你国区正常情况下能用Siri建议吗？🙄️ 能用appleNews吗？🙄️ 能在地区检测为外区的情况下保持国区地图吗🙄️ 非美英区账号，apple tv有电视节目体育节目儿童板块么？🙄️ 想要破解自己动手
> > 
> > 
> > 其他我知道要破解,特别是siri只能搜百度搞了好年没成功, 我刚刚是说apple tv的全功能解锁.... 原来这些不解锁还不能看啊?我只是看看apple的自制剧.我孤陋了...
> 
> 主要目的是把因为地区限定导致缺少的服务和功能加回来

明白了,我还是乖乖继续订阅吧....
