### ISSUE TITLE
quantumultx报错

### ISSUE THREAD

**Issue by JacobYef** [VirgilClyne/iRingo#43]
![IMG_3025](https://user-images.githubusercontent.com/66232946/142953924-e6741880-1685-4aae-a4ed-20eb05c8ad68.PNG)

**Comment by VirgilClyne** [comment]
script-request-header写成script-request-headers了 已修复😭

**Comment by JacobYef** [comment]
哈哈哈，修复的好快鸭
Jacob Ye
Elva Hair

+14147682366 | +8617863930840//
***@***.******@***.***>
www.elvahair.com

f: www.facebook.com/yewenchaojacob
t: www.twitter.com/ElvaHairWigs
l: www.linkedin.com/in/jacob-ye-2192b3117

2021年11月23日 上午9:34，Virgil Clyne ***@***.******@***.***>> 写道：



script-request-header写成script-request-headers了 已修复😭

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FVirgilClyne%2FiRingo%2Fissues%2F43%23issuecomment-976091314&data=04%7C01%7C%7C81871463cbdc4b22085108d9ae216ebf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637732280875718162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=b10IrLGV3YfcLi%2BeE1goPNAvRltaeU%2F5c%2BolKIH7RIQ%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPZKE4RT542VPPPU7ZN6PGDUNLVTLANCNFSM5ISIRQEQ&data=04%7C01%7C%7C81871463cbdc4b22085108d9ae216ebf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637732280875728116%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MKYZuQSRYEKHMJVJ%2B2FSWaZgi4o3OmJzxkDjuHDpXe4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C81871463cbdc4b22085108d9ae216ebf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637732280875728116%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=qoTot8LSNGr3JggZoHyflrVN98nOwYQ%2F2ujmcIdTLpU%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C81871463cbdc4b22085108d9ae216ebf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637732280875738078%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=IDJm07cAnWDE3Gwk%2BtvGP0MCmoIi%2FuIEyPmD4ACZ7cs%3D&reserved=0>.
