### ISSUE TITLE
siri knowledge跳转维基百科出错

### ISSUE THREAD

**Issue by Meonthb** [VirgilClyne/iRingo#44]
无论何种语言，都会强制跳转到英文维基百科，且显示找不到文章

![](https://i.imgur.com/LjmaXCp.jpg)

![](https://i.imgur.com/nj6G53X.jpg)

**Comment by VirgilClyne** [comment]
无法复现啊🤔 我这边是直接跳转到

https://zh.wikipedia.org/wiki/影响因子

具体的系统设置有什么特别的地方吗？比如地区语言？

**Comment by Meonthb** [comment]
> 无法复现啊🤔 我这边是直接跳转到
> 
> [https://zh.wikipedia.org/wiki/影响因子](https://zh.wikipedia.org/wiki/%E5%BD%B1%E5%93%8D%E5%9B%A0%E5%AD%90)
> 
> 具体的系统设置有什么特别的地方吗？比如地区语言？

语言、地区设置如图：

![](https://i.imgur.com/EramDUZ.png)

**Comment by VirgilClyne** [comment]
> 
> 
> 
> 
> 
> 
> > 无法复现啊🤔 我这边是直接跳转到
> 
> > 
> 
> > [https://zh.wikipedia.org/wiki/影响因子](https://zh.wikipedia.org/wiki/%E5%BD%B1%E5%93%8D%E5%9B%A0%E5%AD%90)
> 
> > 
> 
> > 具体的系统设置有什么特别的地方吗？比如地区语言？
> 
> 
> 
> 语言、地区设置如图：
> 
> 
> 
> ![](https://i.imgur.com/EramDUZ.png)
> 
> 
> 
> 

已复现，地区英国，语言简体中文时维基百科链接跳转的域名是en.wikipedia.org
Siri搜索返回的结果内容有问题，无法解决🤪

**Comment by Asstiff** [comment]
也许可以判断 en.wikipedia.org/wiki/ 后的关键字语言，若包含中文，就把前面改写成 zh.wikipedia.org/wiki/   ?

(这个确实蛮难受的。有空的话希望可以研究一下吧）

**Comment by Asstiff** [comment]
@Meonthb 
我没什么正则经验，简单做了一个，可以临时解决一下这个问题。
基本上就是检测到 /wiki/ 后有百分号就改用 zh.wikipedia.org。

https://raw.githubusercontent.com/Asstiff/Google-Canada-to-Normal/main/wiki.conf

**Comment by WordlessEcho** [comment]
倒也不是没有办法，只是如果遇到了别的语言怎么做呢？
https://stackoverflow.com/questions/17564837/how-to-know-if-a-url-is-decoded-encoded
