### ISSUE TITLE
能否支持shadowrocket app ？

### ISSUE THREAD

**Issue by cenyaoyi** [VirgilClyne/iRingo#50]
RT

**Comment by VirgilClyne** [comment]
> RT

有shadowrocket的插件格式教程或者示例吗？

**Comment by cenyaoyi** [comment]
https://github.com/Semporia/TikTok-Unlock
不知道这个能不能参考一下

**Comment by kinaka** [comment]
同求

**Comment by VirgilClyne** [comment]
> 同求

有没有小火箭脚本模块的例子让我看看

**Comment by kinaka** [comment]
> > 同求
> 
> 有没有小火箭脚本模块的例子让我看看

你好！上方的TikTok的不能作为参考吗？因为shadowrocket是去年还是前年才开始支持脚本的，再加上不如其他软件简单，所以网上相关脚本极少😢，如果不能实现的话，也只能说可惜_(:з」∠)_

**Comment by VirgilClyne** [comment]
> > > 同求
> > 
> > 有没有小火箭脚本模块的例子让我看看
> 
> 你好！上方的TikTok的不能作为参考吗？因为shadowrocket是去年还是前年才开始支持脚本的，再加上不如其他软件简单，所以网上相关脚本极少😢，如果不能实现的话，也只能说可惜_(:з」∠)_

我研究研究

**Comment by JOJOforshaun** [comment]
> > > > 同求
> > > 
> > > 
> > > 有没有小火箭脚本模块的例子让我看看
> > 
> > 
> > 你好！上方的TikTok的不能作为参考吗？因为shadowrocket是去年还是前年才开始支持脚本的，再加上不如其他软件简单，所以网上相关脚本极少😢，如果不能实现的话，也只能说可惜_(:з」∠)_
> 
> 我研究研究

喜大普奔小火箭（Build 1569之后）开始兼容surge模块了，除了没有panel之外

**Comment by WordlessEcho** [comment]
因为Shadowrocket已兼容Surge模块，本issue关闭
