### ISSUE TITLE
可否切换WatchOS天气数据源

### ISSUE THREAD

**Issue by hkix** [VirgilClyne/iRingo#51]
>` api.weather.com`:部分Watch（不可修改）
> `weather-data.apple.com`:iOS天气APP、macOS天气小组件、地图、部分Watch（可修改）

watchOS 天气数据源是随机选择，还是有什么规律？用户能手动选择吗？

**Comment by WordlessEcho** [comment]
很遗憾，我和 @VirgilClyne 都没有Apple Watch，没有办法测试

**Comment by WordlessEcho** [comment]
长时间未有回复，关闭issue
Close due to no response
