### ISSUE TITLE
是要保持vpn開啟狀態嗎？

### ISSUE THREAD

**Issue by WaneWean** [VirgilClyne/iRingo#52]
要使用這些服務 需要保持vpn連結的狀態還是不需要

**Comment by offlineface** [comment]
当然需要喽，开启VPN才能通过代理软件进行mitm。

From Dong
________________________________
From: WaneWean ***@***.***>
Sent: Monday, December 20, 2021 1:34:46 AM
To: VirgilClyne/iRingo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VirgilClyne/iRingo] 是要保持vpn_�B幔 (Issue #52)


要使用@些服 需要保持vpnBY的B是不需要

―

**Comment by WaneWean** [comment]
> 当然需要喽，开启VPN才能通过代理软件进行mitm。
> […](#)

明白 謝謝🙏
