### ISSUE TITLE
网络问题导致天气加载慢

### ISSUE THREAD

**Issue by Meonthb** [VirgilClyne/iRingo#53]
开启天气脚本后结果如下

![](https://i.imgur.com/fNevgwS.jpg)

![](https://i.imgur.com/lPbRZOD.jpg)

**Comment by AcaciusJosiah** [comment]
经常出现这样的错误
![c7da760eca429a5f7454089f0fa7d7e](https://user-images.githubusercontent.com/96288219/147716581-c00fed5a-1039-4b7c-babe-16b9fada1a29.jpg)
务

**Comment by SeventhZ** [comment]
> 经常出现这样的错误
> ![c7da760eca429a5f7454089f0fa7d7e](https://user-images.githubusercontent.com/96288219/147716581-c00fed5a-1039-4b7c-babe-16b9fada1a29.jpg)
> 务

我也是总是出现

**Comment by baranwang** [comment]
waqi.info 貌似被墙了

**Comment by VirgilClyne** [comment]
> ~waqi.info 貌似被墙了~ api.waqi.info 被代理时会出现请求超时的问题 #54

并无直接关联，我收到的反馈中，直连或者代理 都会有这种情况发生
api.waqi.info 
jp1n.waqi.info 139.162.71.178 [日本 东京都品川区Linode数据中心]
jp2n.waqi.info 172.105.192.79 [日本 东京都品川区Linode数据中心]
可以尝试自行重定向至jp2n.waqi.info
----

https://api.waqi.info/api/feed/@928/obs.en.json
或
https://api.waqi.info/api/feed/@928/aqi.json
可以尝试用浏览器直接访问上述链接了解哪些线路会导致访问问题

**Comment by WordlessEcho** [comment]
现在的解决方案是设定执行时间，超时后直接终止脚本执行 a6363bf330cc2a4a2710664306e27461e88db99d

**Comment by WordlessEcho** [comment]
Beta版使用本地计算AQI解决了这个问题，请等待正式版更新或是尝试beta版 https://github.com/VirgilClyne/iRingo/issues/107#issuecomment-1195744335
