### ISSUE TITLE
Wikipedia_for_Look_Up.yaml需要clash开启tun模式吗？

### ISSUE THREAD

**Issue by PingZi-Wing** [VirgilClyne/iRingo#55]
已添加相关规则并代理，但在查询时没有维基百科出现。clash for Windows是要开启tun模式才能触发规则吗？

**Comment by VirgilClyne** [comment]
是的，维基百科查询流量不经过本机代理设置中的代理，所以需要tun模式提供虚拟网卡的网关供macOS全部流量通过
