### ISSUE TITLE
Apple Maps 无法使用导航

### ISSUE THREAD

**Issue by gqbre** [VirgilClyne/iRingo#56]
QX，只使用 修改Apple Maps为🇺🇸US 模块
指南针正常显示海拔
Apple Maps 地图数据显示为 Tomtom 正常加载，选择任意地点，点击路线都提示路线不可用（起点默认我的位置），不论哪种交通方式

**Comment by LimnN** [comment]
没办法，Tomtom没有交通数据，Google地图也没国内的交通数据，现在国内交通好像只能高德百度。。二者不可兼得所以我没开这个。。

**Comment by gqbre** [comment]
> 没办法，Tomtom没有交通数据，Google地图也没国内的交通数据，现在国内交通好像只能高德百度。。二者不可兼得所以我没开这个。。
@LimnN Carplay 用户哭晕在厕所
