### ISSUE TITLE
请增加 Apple Music 中 International Broadcasters 的支持

### ISSUE THREAD

**Issue by deplyem** [VirgilClyne/iRingo#58]
首先，非常感谢作者的持续更新 🙏

本人环境为 iOS 15.2，正在使用 Quantumult X 并正在使用以下模块：
🌤天气：Apple_Weather.qxrewrite
📍定位服务：Geo_Services.qxrewrite
🔍Siri与搜索：Siri_Suggestions.qxrewrite
🗺️Apple Maps：Apple_Maps_CN.qxrewrite
📺Apple TV：Apple_TV.qxrewrite
📰Apple News：Apple_News.qxrewrite，规则集:Apple_News_for_Quantumult_X.list 

在使用 Apple Music 中 International Broadcasters 的电台直播功能时出现地区限制提示（如下图）

![AppleMusicRadioRestriction](https://user-images.githubusercontent.com/1827116/150990348-f09488ed-5d06-4906-9f0d-1b329eba0a4c.jpg)

请问能否添加对此功能的支持？
顺颂时祺

**Comment by wangxin6** [comment]
美区 Apple ID 无此问题

**Comment by loyio** [comment]
我也没出现这种问题，可以正常使用

**Comment by deplyem** [comment]
静置一晚后，此问题突然自己神奇地消失了
抱歉劳烦到大家。

![IMG_1980](https://user-images.githubusercontent.com/1827116/151097012-e4fc4958-7fa7-4851-bcc3-43ae2519be47.PNG)

**Comment by VirgilClyne** [comment]
> 静置一晚后，此问题突然自己神奇地消失了 抱歉劳烦到大家。
> 
> ![IMG_1980](https://user-images.githubusercontent.com/1827116/151097012-e4fc4958-7fa7-4851-bcc3-43ae2519be47.PNG)

英国区吗🤔 偶尔触发地区限制可以定位服务改UK 默认都是改US的
