### ISSUE TITLE
空气质量地图不可用

### ISSUE THREAD

**Issue by bryanwongxin** [VirgilClyne/iRingo#59]
只有用了"空气质量数据:[Apple_Weather.sgmodule](https://github.com/VirgilClyne/iRingo/blob/main/sgmodule/Apple_Weather.sgmodule?raw=true)"才能显示us空气质量.

使用"空气质量地图(🆕可用，可行性验证，未修正图层和坐标):[Apple_Weather_Map.sgmodule](https://github.com/VirgilClyne/iRingo/blob/main/sgmodule/Apple_Weather_Map.sgmodule?raw=true)"就显示cn

**Comment by WordlessEcho** [comment]
空气质量地图功能还在做，欢迎贡献代码
