### ISSUE TITLE
允许用户配置Apple TV模块语言

### ISSUE THREAD

**Issue by yuhangrao** [VirgilClyne/iRingo#61]
Apple TV模块默认语言是简体中文，因为账号所在区大部分内容是英语，很多时候点进去会回退到英语，自己也已经习惯英语作为系统语言，所以想请问一下如果启用模块后要让app标签维持英语需要对模块做什么修改呢？

**Comment by lxr760** [comment]
+1


本人设备设置的界面语言是英语    apple tv+本身国区也没有      所以建议apple tv+不要修改语言 保持英文

**Comment by yuhangrao** [comment]
> +1
> 
> 本人设备设置的界面语言是英语 apple tv+本身国区也没有 所以建议apple tv+不要修改语言 保持英文

我自己对脚本简单修改了下，语言改成了英语，你可以直接用https://github.com/yuhangrao/Surge/raw/master/Module/Apple/Apple_TV.sgmodule

**Comment by lxr760** [comment]
> > +1
> > 本人设备设置的界面语言是英语 apple tv+本身国区也没有 所以建议apple tv+不要修改语言 保持英文
> 
> 我自己对脚本简单修改了下，语言改成了英语，你可以直接用https://github.com/yuhangrao/Surge/raw/master/Module/Apple/Apple_TV.sgmodule

老哥，你这个文件是给Surge用的吗？我是圈x，请教下怎么搞

**Comment by WordlessEcho** [comment]
https://github.com/VirgilClyne/iRingo/pull/71#issuecomment-1104689881

Keep issue open as it is not resolved.
问题尚未解决，先保持issue open

**Comment by yuhangrao** [comment]
> https://github.com/VirgilClyne/iRingo/pull/71#issuecomment-1104689881
> 
> 
> 
> Keep issue open as it is not resolved.
> 
> 问题尚未解决，先保持issue open

Surge不是已经可以英语了吗
![image](https://user-images.githubusercontent.com/28585220/165074608-db023743-e23e-4942-9d9a-f98fb4dae386.png)

**Comment by WordlessEcho** [comment]
> 到时候升级Apple TV模块会加BoxJs前端面板提供更多配置选项和功能

**Comment by yuhangrao** [comment]
> > 到时候升级Apple TV模块会加BoxJs前端面板提供更多配置选项和功能

噢
