### ISSUE TITLE
天气app不显示空气质量

### ISSUE THREAD

**Issue by SamTripleOne** [VirgilClyne/iRingo#62]
启用天气模块后，天气app空气质量显示异常
![156984330-0b30f4a6-37ba-4c4b-a840-984c27bfc3be](https://user-images.githubusercontent.com/62505930/157582706-829f9ed5-e91e-470c-a9f1-34b3f6e52589.jpg)
日志如下：
![098f1c1130f8253a323fcec9ab8b684](https://user-images.githubusercontent.com/62505930/156984401-94bdb295-ab88-464b-b945-0eb8583c8733.jpg)
不过彩云天气已不在数据源中
![e44286243aab7c6e36e8ee04efc270a](https://user-images.githubusercontent.com/62505930/156984523-0d6966a9-2b5b-4c81-a50b-27914b76c08e.jpg)

**Comment by offlineface** [comment]
和你情况相同，日志内容大同小异。

**Comment by wangxin6** [comment]
手机的天气可以更新，但是手表没有 AQI。日志基本一样，除了AQ data 是 V1

**Comment by Arlo44** [comment]
大佬还没修复吗

**Comment by Arlo44** [comment]
抓了一下包  EPA_NowCast.2115改为EPA_NowCast.2201就可以了

**Comment by WordlessEcho** [comment]
是bug被更新解决了吗？
