### ISSUE TITLE
打开地图后news失效

### ISSUE THREAD

**Issue by TaiPresident** [VirgilClyne/iRingo#63]
![image](https://user-images.githubusercontent.com/76845019/157789574-c99e0e25-1b2d-4c5a-9337-171f162ba49d.jpeg)
能够正常使用news后，不打开地图能一直使用，流量wifi切换不影响，但打开一次地图后就提示不在支持的地区

**Comment by WordlessEcho** [comment]
> - 注:
>   - 关闭✈️飞行模式后，如再次触发了基于SIM卡的[移动设备网络代码](https://zh.wikipedia.org/wiki/%E7%A7%BB%E5%8A%A8%E8%AE%BE%E5%A4%87%E7%BD%91%E7%BB%9C%E4%BB%A3%E7%A0%81)「MCC / MNC」检测，则Apple News会回到[解锁状态说明](https://github.com/VirgilClyne/iRingo#%E8%A7%A3%E9%94%81%E7%8A%B6%E6%80%81%E8%AF%B4%E6%98%8E)中的解锁失效状态。

[README: Apple News - 激活方式说明](https://github.com/VirgilClyne/iRingo#%E6%BF%80%E6%B4%BB%E6%96%B9%E5%BC%8F-4)
