### ISSUE TITLE
Mac聚焦中的Siri搜索在使用surge时并不生效

### ISSUE THREAD

**Issue by ZhigangSong** [VirgilClyne/iRingo#66]
Siri搜索模块在Mac上使用surge并不生效，而别的模块进可以正常使用。
聚焦搜索等的Siri建议出不来。

根据激活方式中的内容的步骤：
-->保持Wi-Fi或有线网络连接------yes;
-->启用Geo_Services_*.sgmodule模块（🇨🇳CN版除外，可辅以全局代理确保稳定）------yes;
-->重新打开一次地图应用------yes;
-->此时应在Surge的最近请求或Quantumult X的网络活动中观察到:
---->基于网络的地区检测的gspe1-ssl.ls.apple.com链接------yes;
---->激活Siri建议的api.smoot.apple.com/bag链接------NO;
-->执行一次Spotlight搜索，测试「来自APPLE的内容\来自APPLE的建议\Siri建议」是否正常工作------NO;
-->关闭Geo_Services_*.sgmodule模块------没关
-->正常使用------不能正常使用。

**Comment by WordlessEcho** [comment]
> 等待约半小时，「Siri建议」会根据基于网络的地区检测结果向服务器*.smoot.apple.com/bag请求刷新区域设置与功能可用状态

[README: Siri与搜索 - 辅助激活与切换「Siri建议」服务器地区的方式](https://github.com/VirgilClyne/iRingo#%E8%BE%85%E5%8A%A9%E6%BF%80%E6%B4%BB%E4%B8%8E%E5%88%87%E6%8D%A2siri%E5%BB%BA%E8%AE%AE%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%9C%B0%E5%8C%BA%E7%9A%84%E6%96%B9%E5%BC%8F)
