### ISSUE TITLE
Siri2.0  boxjs设置auto region无法显示维基百科

### ISSUE THREAD

**Issue by Clearlove4396777** [VirgilClyne/iRingo#69]
![image](https://user-images.githubusercontent.com/46984082/163904618-bbf9be93-4535-4e1a-97a5-2c4a392f16fe.png)
![image](https://user-images.githubusercontent.com/46984082/163904349-09b78ea4-4311-4b3a-9098-3ff00292b833.png)
![image](https://user-images.githubusercontent.com/46984082/163904371-b357fc74-352b-471a-8746-6144dd60366e.png)

boxjs切换hk之后搜索结果正常
![image](https://user-images.githubusercontent.com/46984082/163904058-90c0aa2d-e3e5-45ae-a4e5-a47477501f3e.png)
![image](https://user-images.githubusercontent.com/46984082/163904074-40ef0269-bf77-45bf-892b-ec956f8a7965.png)

**Comment by WordlessEcho** [comment]
为什么关闭issue？解决了吗？如何解决的？

**Comment by Clearlove4396777** [comment]
> 为什么关闭issue？解决了吗？如何解决的？

前几天点错了😭目前问题依然存在 不知道是不是因为国行机器的原因 🤔我的国行手机和iPad均存在这个问题

**Comment by WordlessEcho** [comment]
请提供日志

**Comment by Clearlove4396777** [comment]
🔔Apple Siri v2.1.0, 开始!
2022/04/26 11:47:08:601  <console>    [JS Console]: ⚠ Apple Siri v2.1.0, Set Environment Variables
2022/04/26 11:47:08:609  <console>    [JS Console]: 🎉 Apple Siri v2.1.0, Set Environment Variables
Settings: object
Settings内容: {"Switch":true,"CountryCode":"AUTO","Domains":["web","app_store","movies","itunes","restaurants","maps"],"Functions":["siri","lookup","safari","spotlight","messages","news","mail","visualintelligence","flightutilities"],"Safari_Smart_History":true}
2022/04/26 11:47:08:612  <console>    [JS Console]: 
🔔Apple Siri v2.1.0, 结束! 🕛 0.016 秒
2022/04/26 11:47:08:613  <console>    [JS Console]: 
2022/04/26 11:47:08:618  <debug>      [QTXJSVirtualMachine]: Engine <6261B98B-32A7-4D5F-AF8C-FBEF6B3FD76D> $done has been called.
2022/04/26 11:47:09:978  <debug>      [QTXTCPPath] The connection-719(inappcheck.itunes.apple.com:443) closed: Attempt to connect to host timed out
2022/04/26 11:47:09:983  <debug>      [QTXTCPConnection] The connection-719(inappcheck.itunes.apple.com:443) lived for 4s, but not even established
2022/04/26 11:47:19:796  <debug>      [QTXJSVirtualMachine]: New engine - 99 <9FC4B93E-9A57-4D1A-A17D-C75D4E0767F4>, active engines - 1.
2022/04/26 11:47:19:862  <console>    [JS Console]: 
🔔BoxJs, 开始!
2022/04/26 11:47:20:336  <console>    [JS Console]: 
🔔BoxJs, 结束! 🕛 0.475 秒
2022/04/26 11:47:20:337  <console>    [JS Console]: 
2022/04/26 11:47:20:348  <debug>      [QTXJSVirtualMachine]: Engine <9FC4B93E-9A57-4D1A-A17D-C75D4E0767F4> $done has been called.
2022/04/26 11:47:25:806  <debug>      [QTXRewriteManager] Regex evaluate URL (REQ) https://api-glb-apne1c.smoot.apple.com/search?alwaysSendTophit=off&calendar=%E5%85%AC%E6%9B%86&card=1&cc=CN&esl=zh-Hant&geosrc=error.fail&kb_ime=zh&key=kakapo4145&l2=11.0&locale=zh_HK&magic=bullseye2%2Cbullseye&q=zj&qtype=suggest_with_results&rm=1&siri_locale=zh-TW&storefront=143441-1%2C29&temp=C&time_zone=Asia%2FShanghai&tm=2&units=SI
2022/04/26 11:47:25:809  <debug>      [QTXRewriteManager] Regex evaluate URL (RSP) https://api-glb-apne1c.smoot.apple.com/search?alwaysSendTophit=off&calendar=%E5%85%AC%E6%9B%86&card=1&cc=CN&esl=zh-Hant&geosrc=error.fail&kb_ime=zh&key=kakapo4145&l2=11.0&locale=zh_HK&magic=bullseye2%2Cbullseye&q=zj&qtype=suggest_with_results&rm=1&siri_locale=zh-TW&storefront=143441-1%2C29&temp=C&time_zone=Asia%2FShanghai&tm=2&units=SI
2022/04/26 11:47:25:810  <debug>      [QTXDataParser] Matched rewrite ^https?:\/\/api.*\.smoot\.apple\.(com|cn)\/search\?(.*) url script-request-header https://raw.githubusercontent.com/VirgilClyne/iRingo/main/js/Siri.request.js for https://api-glb-apne1c.smoot.apple.com/search?alwaysSendTophit=off&calendar=%E5%85%AC%E6%9B%86&card=1&cc=CN&esl=zh-Hant&geosrc=error.fail&kb_ime=zh&key=kakapo4145&l2=11.0&locale=zh_HK&magic=bullseye2%2Cbullseye&q=zj&qtype=suggest_with_results&rm=1&siri_locale=zh-TW&storefront=143441-1%2C29&temp=C&time_zone=Asia%2FShanghai&tm=2&units=SI
2022/04/26 11:47:25:811  <debug>      [QTXDataParser] Matched rewrite ^https?:\/\/api.*\.smoot\.apple\.(com|cn)\/search\?(.*) url script-response-body https://raw.githubusercontent.com/VirgilClyne/iRingo/main/js/Siri.response.js for https://api-glb-apne1c.smoot.apple.com/search?alwaysSendTophit=off&calendar=%E5%85%AC%E6%9B%86&card=1&cc=CN&esl=zh-Hant&geosrc=error.fail&kb_ime=zh&key=kakapo4145&l2=11.0&locale=zh_HK&magic=bullseye2%2Cbullseye&q=zj&qtype=suggest_with_results&rm=1&siri_locale=zh-TW&storefront=143441-1%2C29&temp=C&time_zone=Asia%2FShanghai&tm=2&units=SI
2022/04/26 11:47:25:815  <debug>      [QTXJSVirtualMachine]: New engine - 100 <91481D13-B7A2-4C03-8E22-8A05BE8A33A7>, active engines - 1.
2022/04/26 11:47:25:816  <debug>      [QTXTCPConnection] The connection-720(api-glb-apne1c.smoot.apple.com:443) will be reused, tx 1814, rx 4527
2022/04/26 11:47:25:823  <info>       [QTXTCPPath] New connection-724(api-glb-apne1c.smoot.apple.com:443) reused from connection-720 original connection-720 
2022/04/26 11:47:25:874  <console>    [JS Console]: 
🔔Apple Siri v2.1.1, 开始!
2022/04/26 11:47:25:879  <console>    [JS Console]: ⚠ Apple Siri v2.1.1, Set Environment Variables
2022/04/26 11:47:25:891  <console>    [JS Console]: 🎉 Apple Siri v2.1.1, Set Environment Variables
Settings: object
Settings内容: {"Switch":true,"CountryCode":"HK","Domains":["web","app_store","movies","itunes","restaurants","maps"],"Functions":["siri","lookup","safari","spotlight","messages","news","mail","visualintelligence","flightutilities"],"Safari_Smart_History":true}
2022/04/26 11:47:25:895  <console>    [JS Console]: 
🔔Apple Siri v2.1.1, 结束! 🕛 0.023 秒
2022/04/26 11:47:25:897  <console>    [JS Console]: 
2022/04/26 11:47:25:900  <debug>      [QTXJSVirtualMachine]: Engine <91481D13-B7A2-4C03-8E22-8A05BE8A33A7> $done has been called.
2022/04/26 11:47:26:033  <debug>      [QTXRewriteManager] Regex evaluate URL (REQ) https://api-glb-apne1c.smoot.apple.com/search?alwaysSendTophit=off&calendar=%E5%85%AC%E6%9B%86&card=1&cc=CN&esl=zh-Hant&geosrc=error.fail&kb_ime=zh&key=kakapo4145&l2=11.0&locale=zh_HK&magic=bullseye%2Cbullseye2&q=zjl&qtype=suggest_with_results&rm=1&siri_locale=zh-TW&storefront=143441-1%2C29&temp=C&time_zone=Asia%2FShanghai&tm=2&units=SI
2022/04/26 11:47:26:036  <debug>      [QTXRewriteManager] Regex evaluate URL (RSP) https://api-glb-apne1c.smoot.apple.com/search?alwaysSendTophit=off&calendar=%E5%85%AC%E6%9B%86&card=1&cc=CN&esl=zh-Hant&geosrc=error.fail&kb_ime=zh&key=kakapo4145&l2=11.0&locale=zh_HK&magic=bullseye%2Cbullseye2&q=zjl&qtype=suggest_with_results&rm=1&siri_locale=zh-TW&storefront=143441-1%2C29&temp=C&time_zone=Asia%2FShanghai&tm=2&units=SI
2022/04/26 11:47:26:037  <debug>      [QTXDataParser] Matched rewrite ^https?:\/\/api.*\.smoot\.apple\.(com|cn)\/search\?(.*) url script-request-header https://raw.githubusercontent.com/VirgilClyne/iRingo/main/js/Siri.request.js for https://api-glb-apne1c.smoot.apple.com/search?alwaysSendTophit=off&calendar=%E5%85%AC%E6%9B%86&card=1&cc=CN&esl=zh-Hant&geosrc=error.fail&kb_ime=zh&key=kakapo4145&l2=11.0&locale=zh_HK&magic=bullseye%2Cbullseye2&q=zjl&qtype=suggest_with_results&rm=1&siri_locale=zh-TW&storefront=143441-1%2C29&temp=C&time_zone=Asia%2FShanghai&tm=2&units=SI
2022/04/26 11:47:26:038  <debug>      [QTXDataParser] Matched rewrite ^https?:\/\/api.*\.smoot\.apple\.(com|cn)\/search\?(.*) url script-response-body https://raw.githubusercontent.com/VirgilClyne/iRingo/main/js/Siri.response.js for https://api-glb-apne1c.smoot.apple.com/search?alwaysSendTophit=off&calendar=%E5%85%AC%E6%9B%86&card=1&cc=CN&esl=zh-Hant&geosrc=error.fail&kb_ime=zh&key=kakapo4145&l2=11.0&locale=zh_HK&magic=bullseye%2Cbullseye2&q=zjl&qtype=suggest_with_results&rm=1&siri_locale=zh-TW&storefront=143441-1%2C29&temp=C&time_zone=Asia%2FShanghai&tm=2&units=SI
2022/04/26 11:47:26:044  <debug>      [QTXTCPConnection] The connection-721(api-glb-apne1c.smoot.apple.com:443) will be reused, tx 1812, rx 4527
2022/04/26 11:47:26:044  <debug>      [QTXJSVirtualMachine]: New engine - 101 <E8AB05C8-C44F-47B9-ACC9-AEC6510A3313>, active engines - 1.
2022/04/26 11:47:26:051  <info>       [QTXTCPPath] New connection-725(api-glb-apne1c.smoot.apple.com:443) reused from connection-721 original connection-721 
2022/04/26 11:47:26:100  <console>  

🔔Apple Siri v2.1.1, 开始!
2022/04/26 11:47:26:102  <debug>      [QTXDataParser] Rewrite body bytes length 5741 https://api-glb-apne1c.smoot.apple.com/search?alwaysSendTophit=off&calendar=%E5%85%AC%E6%9B%86&card=1&cc=CN&esl=zh-Hant&geosrc=error.fail&kb_ime=zh&key=kakapo4145&l2=11.0&locale=zh_HK&magic=bullseye2%2Cbullseye&q=zj&qtype=suggest_with_results&rm=1&siri_locale=zh-TW&storefront=143441-1%2C29&temp=C&time_zone=Asia%2FShanghai&tm=2&units=SI
2022/04/26 11:47:26:104  <console>    [JS Console]: ⚠ Apple Siri v2.1.1, Set Environment Variables
2022/04/26 11:47:26:109  <debug>      [QTXJSVirtualMachine]: New engine - 102 <5B474A98-C796-460B-893B-21B273987615>, active engines - 2.
2022/04/26 11:47:26:124  <console>    [JS Console]: 🎉 Apple Siri v2.1.1, Set Environment Variables
Settings: object
Settings内容: {"Switch":true,"CountryCode":"HK","Domains":["web","app_store","movies","itunes","restaurants","maps"],"Functions":["siri","lookup","safari","spotlight","messages","news","mail","visualintelligence","flightutilities"],"Safari_Smart_History":true}
2022/04/26 11:47:26:128  <console>    [JS Console]: 
🔔Apple Siri v2.1.1, 结束! 🕛 0.029 秒

> 请提供日志

**Comment by VirgilClyne** [comment]
你该不会 系统地区设置为中国大陆的情况下 boxjs里设置了自动？

**Comment by Clearlove4396777** [comment]
> 

地区设置一直是hk
