### ISSUE TITLE
WAQI APIv2无法检测到附近的监测站

### ISSUE THREAD

**Issue by Danrusty** [VirgilClyne/iRingo#76]
重写模块在quanx已经订阅了
![15296862-1ACC-4AC8-94EB-B57BE6EB5F3D](https://user-images.githubusercontent.com/43928994/164728482-fb1c232a-647a-4eeb-9683-fd970b0e3457.png)
资源解析器也打开了，但打开天气app以后默认的第一个本地天气aqi始终无法被修改成us区域，provider还是默认的Qweather.
![0B24C8C7-3F2B-4B1F-8393-CBE94526F432](https://user-images.githubusercontent.com/43928994/164728644-240f72e5-279f-4f30-b4f1-e2328e3d3423.png)

查看quanx的日志如下：

🔔Apple Weather AQI v3.1.0, 开始!
2022/04/22 21:51:00:932  <console>    [JS Console]: ⚠ Apple Weather AQI v3.1.0, Set Environment Variables
2022/04/22 21:51:00:941  <console>    [JS Console]: 🎉 Apple Weather AQI v3.1.0, Set Environment Variables
Settings: object
Settings内容: {"Switch":true,"NextHour":{"Switch":true},"AQI":{"Switch":true,"Mode":"WAQI Private","Location":"Station","Auth":"申请的私人token","Scale":"EPA_NowCast.2201"},"Map":{"AQI":true}}
2022/04/22 21:51:00:945  <console>    [JS Console]: 🚧 Apple Weather AQI v3.1.0
Params: {"ver":"v2","language":"en-US","lat":"30.503","lng":"114.417"}
2022/04/22 21:51:00:947  <console>    [JS Console]: 🚧 Apple Weather AQI v3.1.0, providerName = QWeather
2022/04/22 21:51:00:949  <console>    [JS Console]: 🎉 Apple Weather AQI v3.1.0, 需要替换AQI
2022/04/22 21:51:00:950  <console>    [JS Console]: 🚧 Apple Weather AQI v3.1.0, 工作模式: waqi.info 私有API
2022/04/22 21:51:00:952  <console>    [JS Console]: 🚧 Apple Weather AQI v3.1.0, 定位精度: 观测站
2022/04/22 21:51:00:953  <console>    [JS Console]: ⚠ Apple Weather AQI v3.1.0, WAQI
input: {"api":"v2","lat":"30.503","lng":"114.417"}
2022/04/22 21:51:00:955  <console>    [JS Console]: ⚠ Apple Weather AQI v3.1.0, Get WAQI Request, type: Nearest
2022/04/22 21:51:00:957  <console>    [JS Console]: 获取最近站点
2022/04/22 21:51:00:959  <console>    [JS Console]: ⚠ Apple Weather AQI v3.1.0, Get WAQI Data, type: Nearest
2022/04/22 21:51:02:293  <console>    [JS Console]: 🎉 Apple Weather AQI v3.1.0, GetData:Nearest完成
idx: null
观测站: null
AQI: null
2022/04/22 21:51:02:296  <console>    [JS Console]: 🚧 Apple Weather AQI v3.1.0, WAQI
output: {"station":null,"idx":null}
2022/04/22 21:51:02:299  <console>    [JS Console]: ⚠ Apple Weather AQI v3.1.0, WAQI
input: {"token":"decff1be15d478de35a7d1dedff89d086a8c0cf3","idx":null}
2022/04/22 21:51:02:301  <console>    [JS Console]: ⚠ Apple Weather AQI v3.1.0, Get WAQI Request, type: StationFeed
2022/04/22 21:51:02:302  <console>    [JS Console]: 获取站点信息
2022/04/22 21:51:02:304  <console>    [JS Console]: ⚠ Apple Weather AQI v3.1.0, Get WAQI Data, type: StationFeed
2022/04/22 21:51:02:475  <console>    [JS Console]: 🎉 Apple Weather AQI v3.1.0, GetData:StationFeed完成
idx: undefined
观测站: undefined
AQI: undefined
2022/04/22 21:51:02:478  <console>    [JS Console]: 🚧 Apple Weather AQI v3.1.0, WAQI
output: null
2022/04/22 21:51:02:482  <console>    [JS Console]: ⚠️ Apple Weather AQI v3.1.0, outputAQI检测
AQI data v2
2022/04/22 21:51:02:484  <console>    [JS Console]: ⚠️ Apple Weather AQI v3.1.0, classifyAirQualityLevel, Error
aqiIndex: undefined
2022/04/22 21:51:02:487  <console>    [JS Console]: 
❗️Apple Weather AQI v3.1.0, 错误!
RangeError: Invalid Date
2022/04/22 21:51:02:489  <console>    [JS Console]: 
🔔Apple Weather AQI v3.1.0, 结束! 🕛 1.568 秒
感觉好像是没有获取到最近的监测站。
但是手动添加的其他区域均可以正常显示：
![030D3950-F101-4759-ABCF-7E0188F243A8](https://user-images.githubusercontent.com/43928994/164728992-6b367eac-923d-4741-b27f-0b01146c5355.png)
非常奇怪。求大佬帮忙

**Comment by Danrusty** [comment]
系统版本15.4

**Comment by Danrusty** [comment]
> 日志里有你的私人信息（lat, lng, token），记得保护一下
没关系，就一个经纬度。我还怀疑是不是有可能因为我在的位置附近某个范围没有监测站所以找不到nearest station，然后报错了。但是我单独添加武汉市，它又找得到附近孝感的监测点，就很奇怪，我搞了一个晚上都没解决

**Comment by WordlessEcho** [comment]
token你要删掉，你用的私有token，我建议你现在去重新申请一下
然后说回正题，我发现APIv2不能检测到附近的监测站，但APIv1可以，所以是API的问题，我觉得可以考虑做一个workaround @VirgilClyne

**Comment by Danrusty** [comment]
> 日志里有你的私人信息（lat, lng, token），记得保护一下

感谢，把token删掉了。刚还没注意。经纬度我就留着了，我还怀疑是不是因为武汉附近就两个监测点，它搜索监测站的范围有个阈值，然后没找到就报错了。但是我单独添加武汉的话又能找到，就非常奇怪

**Comment by Danrusty** [comment]
好嘞，我先试试，感谢大佬

**Comment by Danrusty** [comment]
确实是这样。已解决。

**Comment by WordlessEcho** [comment]
Keep issue open as it is not resolved.
问题尚未解决，先保持issue open

**Comment by Danrusty** [comment]
> Keep issue open as it is not resolved. 问题尚未解决，先保持issue open

好的，抱歉表述刚才不准确，我的问题已解决，但bug尚待修复。

**Comment by WordlessEcho** [comment]
你的编辑记录也要记得删掉 @Danrusty 
![image](https://user-images.githubusercontent.com/12007025/165079138-e46719b1-53b1-43e5-be57-750c1f878b85.png)

**Comment by Danrusty** [comment]
> 你的编辑记录也要记得删掉 @Danrusty ![image](https://user-images.githubusercontent.com/12007025/165079138-e46719b1-53b1-43e5-be57-750c1f878b85.png)

感谢提醒。已删除。

**Comment by gdopera** [comment]
> 日志里有你的私人信息（lat, lng, token），记得保护一下

老大又见到你了

**Comment by WordlessEcho** [comment]
临时解决方案：
申请API token：[Air Quality Open Data Platform API Token Request Form](https://aqicn.org/data-platform/token/cn/#/)
将定位精度切换为「城市」

**Comment by WordlessEcho** [comment]
已在v4版天气模块中修复
