### ISSUE TITLE
编写更详细的入门教程

### ISSUE THREAD

**Issue by WordlessEcho** [VirgilClyne/iRingo#78]
- 放在开头
- 按照代理软件分节
- 从MitM教到启用模块

# 参与说明
将截图放入[./ScreenShots/tutorial/<代理软件名>](https://github.com/VirgilClyne/iRingo/tree/main/ScreenShots/tutorial)中，然后写在[README](https://github.com/VirgilClyne/iRingo/blob/main/README.md)上相应的位置

# 编写及认领状态
- [ ] Loon
- [ ] Quantumult X
- [ ] Surge
- [ ] Shadowrocket ( @WordlessEcho )
- [ ] Stash ( @shindgewongxj )
- [ ] Clash

**Comment by shindgewongxj** [comment]
我想认领Stash教程编写。

**Comment by WordlessEcho** [comment]
Discontinued.
