### ISSUE TITLE
更新 weather 后，Apple Watch 不显示源图标。

### ISSUE THREAD

**Issue by Asstiff** [VirgilClyne/iRingo#82]
![image](https://user-images.githubusercontent.com/46558763/165511972-231784f7-94ea-4aa6-bdf7-aad43c553946.png)

不过 iPhone 上确实是显示了。

**Comment by WordlessEcho** [comment]
原来用的是这个
https://github.com/VirgilClyne/iRingo/blob/f7d874118169433ccff40f59d7e049b60291e6d1/js/Weather.js#L348
我看彩色也挺好，要不做个API版本判断？
@VirgilClyne

**Comment by VirgilClyne** [comment]
> 原来用的是这个
> 
> https://github.com/VirgilClyne/iRingo/blob/f7d874118169433ccff40f59d7e049b60291e6d1/js/Weather.js#L348
> 
> 
> 我看彩色也挺好，要不做个API版本判断？
> @VirgilClyne

在做了在做了
