### ISSUE TITLE
建议缩减日志输出量

### ISSUE THREAD

**Issue by A1exMinatoooo** [VirgilClyne/iRingo#87]
天气重写会输出大量的日志，导致想要排查其他插件的错误时需要先关闭，有些许不便。可否在BoxJS增加开关来调整是否输出日志呢

**Comment by WordlessEcho** [comment]
可以按照[`851682b`里的iRingo.beta.boxjs.json](https://github.com/VirgilClyne/iRingo/commit/851682b71b98db851e7221383fba6733e11f216e#diff-1322a28297002bc504d0c6c93b9c8c38245984a078935dfb5d087fd0dfd9f497)先编写BoxJS设置。然后按照[`06bdd8a`里Weather.beta.js的第8行](https://github.com/VirgilClyne/iRingo/commit/06bdd8a79488bb7e2f7b0938e06e2662f0231bcb#diff-91bc72dbf510c049f3912347c9d77576593b1d0cd750b51df447848ce1b9ee5dR8)添加默认值。按[`6da7ea5`将String转为Boolean值](https://github.com/VirgilClyne/iRingo/commit/6da7ea51ec4eab88818975ad68caa3fc30300b1a#diff-91bc72dbf510c049f3912347c9d77576593b1d0cd750b51df447848ce1b9ee5dR103)后，再参照[`06bdd8a`里Weather.beta.js的第510行](https://github.com/VirgilClyne/iRingo/commit/06bdd8a79488bb7e2f7b0938e06e2662f0231bcb#diff-91bc72dbf510c049f3912347c9d77576593b1d0cd750b51df447848ce1b9ee5dR510)给打印日志添加判断条件即可。
也欢迎有能力的人提交pr。

**Comment by VirgilClyne** [comment]
> 

我宁可在正式版里手动移除所有log，为了开关log加判断点，会让脚本跑慢0.03ms的🤣

**Comment by WordlessEcho** [comment]
也行，就这样

**Comment by VirgilClyne** [comment]
> 天气重写会输出大量的日志，导致想要排查其他插件的错误时需要先关闭，有些许不便。可否在BoxJS增加开关来调整是否输出日志呢

看了一下，关注了五座城市，每天日志约200kb左右，这多吗🤔？

**Comment by WordlessEcho** [comment]
991adf4e67b40977b2c29292a35d75219006464f
