### ISSUE TITLE
dns分流插件quanx使用小问题

### ISSUE THREAD

**Issue by Ranlyliu** [VirgilClyne/iRingo#93]
# 百度 静态资源
server = /*.bdimg.com/180.76.76.76
server = /*.bdstatic.com/180.76.76.76

dns小作品里的这两行会影响百度贴吧没有网络，加载图片视频加载不出来，我是小白说错了的话，大佬别喷

**Comment by Ranlyliu** [comment]
> 百度
server = /*.baidu/180.76.76.76
server = /*.baidu.com/180.76.76.76

还是加载不出来不能刷新首页内容，删掉这两个有改善

**Comment by WordlessEcho** [comment]
小作品请反馈到这里 https://github.com/VirgilClyne/VirgilClyne/
